src/main/java/com/dreammaster/baubles/OvenGlove.java
Remove only own resist
Try to not override another's resist
https://github.com/GTNewHorizons/NewHorizonsCoreMod/issues/10
"potionAmbient = true" - makes particles effect  transparent (also adds MORE compatibility). Set to false if you wanna use bold particles.
=> OvenGloves FireProtection compatibility mode

src/main/java/com/dreammaster/config/CoreModConfig.java, src/main/java/com/dreammaster/main/MainRegistry.java, src/main/java/com/dreammaster/modfixes/minetweaker/MinetweakerFurnaceFix.java
GTNewHorizons/NewHorizons#2805
Also allows this mod's `CustomFuels` XML files to override the vanilla burn times.
Mostly useful to override burn times for items where `material == WOOD`, since the material check normally takes precedence over Minetweaker and custom fuels.
=> Override any vanilla burn times with Minetweaker

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
This addresses https://github.com/GTNewHorizons/NewHorizons/issues/2890, with this change biomass production is now energy positive and can be used to create electricity, very much like biogas.
Since we can't make recipes for the forestry fermenter that have a different time or energy usage, we have to take all the fermenter recipes from forestry and add them into the gregtech brewing machine. Then we can adjust the ratio of the biomass produced and the ethanol from biomass. This makes the forestry 'Fermenter' and 'Still' obsolete though, since they are now worse than the gt machines.
We add all forestry fermenter fermenter recipes into gregtech brewery with the following changes:
- Turn conversion rate from "40L biomass to 12L Ethanol" to "40L biomass to 20L Ethanol"
- Double the biomass …
=> Ethanol production with forestry fermenter costs too much energy

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Possibility of using all LuV circuits (except for nano mainframe) in the Quantum Suit crafting.
=> added circuits for quantum suit recipe

src/main/java/com/dreammaster/gthandler/accelerator/GT_MetaTileEntity_WorldAccelerator.java
If you configure the range to 1 in block mode, then switch to TE mode, HV WA consumes 1024EU/t. If you use the default, i.e. range max, it will consume 3072EU/t. The reduction in energy cost goes even higher for EV+ WA (max 85% reduction for ZPM WA, see screenshot below). The behavior persists after server restart.
=> Fix world world accelerator power consumption

build.gradle, src/main/java/com/dreammaster/coremod/DepLoader.java, src/main/java/com/dreammaster/coremod/DownloadProgressDialog.java, src/main/java/com/dreammaster/coremod/DreamCoreMod.java
1. Load stuff to download from config/dependencies.json. Format is as below.
```json
[
{
"path": "mods/AngerMod-1.7.10-0.6.jar",
"url": "http://downloads.gtnewhorizons.com/Mods_for_Twitch/AngerMod-1.7.10-0.6.jar"
},
{
"path": "mods/1.7.10/Baubles-1.7.10-1.0.1.12.jar",
"url": "http://downloads.gtnewhorizons.com/Mods_for_Twitch/Baubles-1.7.10-1.0.1.12.jar"
}
]
```
2. Do nothing if
1. dependencies.json is not present
2. dependencies.json is empty
3. all dependencies specified are present
3. If a previous download fails half way, any files downloaded successfully will not be downloaded again, but the one that failed will have to restart from scratch.
4. Destination directories will be automatically created if it is not present
5. Destination directories are relative to .minecraft directory, …
=> Add deploader functionality

build.gradle, src/main/java/com/dreammaster/config/CoreModConfig.java, src/main/java/com/dreammaster/main/MainRegistry.java, src/main/java/com/dreammaster/modfixes/thaumcraft/ReuseWardFocusFix.java
Support for GTNewHorizons/GT-New-Horizons-Modpack#6846
This is a fix targeting a specific recipe. It can be expanded to allows ingredient reusing in any arcane recipes, but for now let's keep it simple.
=> Reuse warding focus when crafting warded glass

src/main/java/com/dreammaster/gthandler/CoreMod_ProcessingArrayRecipeLoader.java
fix so that ZPM+ forming presses will work in PA
=> fix meta range for press recipe in PA

src/main/java/com/dreammaster/gthandler/GT_Loader_Wires.java, src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
This was done due to uncraftability of Trinium and HSSS coils. Also, some recipes werent in line with other coil recipes.
=> add new coil recipes and streamline old ones

src/main/java/com/dreammaster/gthandler/multiAirFilter/GT_MetaTileEntity_AirFilter.java
According to boubou's calculation and feedback from discord folks, this new formula seems to give a satisfying number for HV+.
New formula: each muffler reduce `300 * displayed turbine efficiency * Floor(2.5 ^ min(multi tier, muffler tier)) / 10` gibbl every second
New Requirement: Power tier of machine MUST match the tier of muffler or the muffler would underclock.
Key indicators: 
* Standard HV equipments: ~4k gibbl/second 
* Standard EV equipments: 15k~20k gibbl/second
* UHV equipments: ~9m gibbl/second
* Turbine last twice as long as it would inside a turbine generating the same amount of EU as the air filter consumes.
Calculation: https://discord.com/channels/181078474394566657/502566698142924811/826237068845383691
Feedback: …
=> Buff air filter multi's effectiveness

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java, src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7752, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7986.
Changed which ones are x5 and x8, since the ones with durability don't work right in the assembler.
=> Fix neutron reflectors

build.properties, src/main/java/com/dreammaster/bartworksHandler/PyrolyseOvenLoader.java, src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java, src/main/java/com/dreammaster/main/MainRegistry.java
Add helper class to create pyrolyse oven recipes for `logWood`. Where this class is currently registered to run (GT post-load) works; I know that GT++ postinit will also work. Earlier than that, some woods may not have been registered in the ore dictionary yet. Let me know if there is a better place to put this code.
I've tested that with this change, all `logWood` woods work in the pyrolyse oven. This will allow us to delete the BW and GT dynamic pyrolyse recipe generation code which is causing lag.
I deleted the `ExtraTrees` pyrolyse recipes in `GT_MachineRecipeLoader` because they are just a copy of the method the new code is calling:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/oreprocessing/ProcessingLog.java#L97-L107
so that code …
=> Add helper to create pyrolyse oven recipes for logWood

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java, src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java, src/main/java/com/dreammaster/gthandler/GT_Recipe_Remover.java
Also add assembler recipes for the blocks
Also resort the RR file alphabetically and use vars for repeated strings
Also changed to delayed version for the removed recipes. All the recipes in the crafting file are buffered, so it should be ok?
This should fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7736
The ztones script file needs to be removed after merging.
=> Move Ztones from script to coremod

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Hopefully this is acceptable, I couldn't find a better place for  those lines of code.
-What does it do?
Adds the ability for assemblers to manufacture Computer Screen Covers and AE2 Illuminated Panels of which those Covers are a subcomponent.
-Why was this made?
Didn't have an assembler recipe. Makes them autocraftable now without tools.
-Did you test this?
Yes with the latest build.
-Note from me:
Unfortunately due to my experience, I don't actually know how to oredict dyes, so I went with something I could reference in the code.
=> Update GT_MachineRecipeLoader.java to include Assembler Recipes for AE2 illuminated Panels and Computer Monitor Covers

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Replaces Filled Map with Empty Map in the Assembler Recipe. Also adds a space between the lines 2517 and 2518 so it stays uniform (I previously added to this space).
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8403
=> Alters Navigation Upgrade from OC to use Empty Map instead of Filled Map

src/main/java/com/dreammaster/gthandler/CustomItemList.java, src/main/java/com/dreammaster/gthandler/GT_Loader_Items.java, src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Cut the recursion crap from current recipes for the AE2 cells:
All the circuits are oredicted, and there is the usual declination for lead/tin/soldering alloy as fluid. Previous recursive recipes remain as is, and should only be considered when one wants to upgrade old cells into a bigger one.
=> add non recursive recipes for AE cells

src/main/java/com/dreammaster/modcustomdrops/CustomDropsHandler.java
fix this warning:
<details>
<summary>log</summary>
```
[01:11:08 WARN]: java.lang.IllegalArgumentException: bound must be positive
[01:11:08 WARN]:        at java.util.Random.nextInt(Random.java:388)
[01:11:08 WARN]:        at com.dreammaster.modcustomdrops.CustomDropsHandler.HandleCustomDrops(CustomDropsHandler.java:276)
[01:11:08 WARN]:        at com.dreammaster.modcustomdrops.CustomDropsHandler.onMobDrops(CustomDropsHandler.java:208)
[01:11:08 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler_890_CustomDropsHandler_onMobDrops_LivingDropsEvent.invoke(.dynamic)
[01:11:08 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[01:11:08 WARN]:        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[01:11:08 …
```
=> fix random values with bound of 1 being oob

src/main/java/com/dreammaster/gthandler/multiAirFilter/GT_MetaTileEntity_AirFilterBase.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9106
Even if this PR fixes it, i find it a bit cumbersome to not rely on the translation manager to get the name of the blocks for the tooltip because it's not yet initialized or something.
=> fixed  GTNewHorizons/GT-New-Horizons-Modpack#9106

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java, src/main/java/com/dreammaster/scripts/IScriptLoader.java, src/main/java/com/dreammaster/scripts/ScriptBiblioCraft.java, src/main/java/com/dreammaster/scripts/ScriptBiblioWoodsBoP.java, src/main/java/com/dreammaster/scripts/ScriptBiblioWoodsForestry.java, src/main/java/com/dreammaster/scripts/ScriptBiblioWoodsNatura.java, src/main/java/com/dreammaster/scripts/ScriptHoloInventory.java, src/main/java/com/dreammaster/scripts/ScriptSleepingBags.java, src/main/java/com/dreammaster/scripts/ScriptSpiceOfLife.java
This requires:
- sleeping bag 1.1.2GTNH
- https://github.com/GTNewHorizons/HoloInventory/pull/15
- https://github.com/GTNewHorizons/SpiceOfLife/pull/18
- https://github.com/GTNewHorizons/Hodgepodge/pull/48 and https://github.com/GTNewHorizons/Hodgepodge/pull/45
- https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9257 and https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9263
For the biobliocraft/bibliowoods stuff, it needs extensive testing, as i translated the script into java via a python script, so idk if everything went well, but i didn't spot any error. But i remember that @Dream-Master told me that after the sledgehammer, some bibliocraft stuff is missing recipes.
Let me know which recipes and i'll add them back. I also didn't cached at all the lookups in the …
=> Port of Holo-Inventory, SpiceOfLife, BiblioCraft and sleeping bags scripts into code.

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
added recipes of the mixed metal ingot into the assembler, so it reduces the need of molecular assemblers if you need to spam them:
=> add mixed metal ingot recipes in the assembler

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
As discussed in DMs with @Dream-Master.
I don't remove the crafting recipes in this PR yet because i think this should be changed in the same PR as the rework of LV+ solars in the avaritia crafting table, to keep some consistency.
for reference, the recipes for 1EU and 8EU solars are located here: https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/97fb4cd5610f6bccdc077e04d17b98d2c4060e34/src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java#L98-L100
=> buff assembler recipes for 1EU and 8EU solars

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Allows the player to use their Sunnarium dust to divide into 9 and then get the Sunnarium Piece, which was unrealistically obtainable due to the recent MT changes
Fixes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9913
Also provides backwards combability in any off chances of some Sunnarium changes/bugs/oversights.
=> Tiny Sunnarium Dust > Sunnarium Piece

src/main/java/com/dreammaster/oredict/OreDictHandler.java
- Registers "Nether Log" from Pam's Harvest the Nether to `logWood`
- General cleanup of `OreDictHandler`, it is not needed to fetch the same item/block from the game registry multiple times...
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9761.
=> Clean up `OreDictHandler`

src/main/java/com/dreammaster/bartworksHandler/BW_Recipe_Loader.java, src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
- Replaced the LV-tier Soldering Alloy in Assembly Line recipes with a higher tier, more complex solder that fits progression better.
Requires https://github.com/GTNewHorizons/GTplusplus/pull/193. See that PR for more information.
=> Replace Assline Solder in CoreMod Recipes

src/main/java/com/dreammaster/gthandler/GT_Loader_Wires.java
Osmiridum:
- 8A LuV for 1x
- 2EU/A loss uninsulated, 1EU/A insulated
HSS-E:
- 6A LuV for 1x
- 4EU/A loss uninsulated, 2EU/A insulated
=> Add Osmiridium, HSS-E LuV cables

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Adds a simple fluid extraction recipe for the Gallium Arsenide Crystal.
Explanation is here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10331
TLDR: The fluid is used for QBITs and the current way to obtain it is convoluted for no reason.
Recipe time/tier/duration is just the same as the ingot.
=> Adds AsGa crystal fluid extraction

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Adjusted as to make eternal coils for a full DTPF more obtainable
- Spacetime recipe yield 72L->144L
- Spacetime recipe duration 250s->100s
- Spacetime recipe 9216L->2304L molten inf
- Molten inf recipe duration 500s->250s
- Molten inf recipe 114062L->57031L resplendent catalyst
=> Multiple endgame DTPF adjustments

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
- Added EBF recipes for the ores that were buffed in the respective PR in GT5-Unofficial.
Meant for [#1146](https://github.com/GTNewHorizons/GT5-Unofficial/pull/1146). The new ores which had their turbine numbers greatly buffed will get EBF recipes, with the same time per ingot as Oriharukon, but an appropriate EU/t and coil tiering for each one.
=> Add EBF Recipes to Space Ores for Turbines

src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
Changed LUV-UEV Fluid Extractor recipes to match changed recipes from LV-IV in PR:
https://github.com/GTNewHorizons/GT5-Unofficial/pull/1166
New recipe (new orders):
=> Re-erange Fluid Extractor recipes

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Buffed the first tesseract recipe to take a zpm circuit instead of of the GG one and added a second, more advanced recipe
=> Tesseract recipe adjustment

src/main/java/com/dreammaster/gthandler/GT_Recipe_Remover.java, src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java, src/main/java/com/dreammaster/scripts/ScriptLoader.java
Recipes are simple following example of normal co-processor
4x takes IV circuits
16x takes UV circuits
=> Replace 4x and 16x co-processor recipes

src/main/java/com/dreammaster/loginhandler/LoginHandler.java
Server crashes otherwise due to not being able find the client.
=> Fix import to also work on serverside

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java, src/main/java/com/dreammaster/scripts/ScriptJABBA.java
No recursive Jabba upgrade crafting anymore
add control circuits to machine recipes
change Chrome to Rhodium-Plated Palladium if Bartworks is loaded
=> Jabba upgrades

src/main/java/com/dreammaster/auxiliary/NEIGTNewHorizonsConfig.java
So I made this PR a few days ago to try and "fix" the fake circuits and let them be used as OreDict wildcards: https://github.com/GTNewHorizons/GT5-Unofficial/pull/1350
But we don't really need to/care about supporting that, plus it'd apparently break the IC2 circuits, PLUS it wouldn't work anyway because AE2 just doesn't play nice on processing patterns for oreDicted circuits.
So we agreed that we should just hide these circuits from NEI. There's no reason for the player to see them anyway, they're really just an internal patch, and hiding them prevents players from *trying* to use them in that non-functional way.
@GlodBlock for your blessing since these are your circuits.
=> Hid fake circuits from NEI

src/main/java/com/dreammaster/scripts/ScriptAvaritiaAddons.java
related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11226
it conflicts with Obsidian Chest assembler recipe so I have to add a circuit on modpack side
=> Add Compressed Chest assembler recipe

src/main/java/com/dreammaster/scripts/IScriptLoader.java, src/main/java/com/dreammaster/scripts/ScriptEnderIO.java, src/main/java/com/dreammaster/scripts/ScriptLoader.java
Adds a recipe in the dire crafting table for https://github.com/GTNewHorizons/EnderIO/pull/83
I intentionally did not add usual costly items to gate it only at UV, main gate being the cosmic neutronium in the endest pearl, as you either need the neutron collector to make some or to go mine small black plutonium ores on triton which is a T6 rocket.
=> added extreme shaped recipe for the creative staff of travelling

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
inductor smd is the smd verison of small coils. the following is what every tier's circuit accepts:
processor circuit: small coils, inductor smd, inductor asmd
nano circuit: inductor smd, inductor asmd
quantum circuit: inductor smd, inductor asmd
crystal circuit: inductor asmd
wetware circuit: inductor asmd, inductor xsmd
bio circuit: inductor asmd, inductor xsmd
=> replace small coils in high tier circuits with inductor smd

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
Added recipes for the cable diodes UHV to MAX. Bartworks can't autogenerate them because the high tier cables are defined in this mod.
Opened https://github.com/GTNewHorizons/bartworks/pull/231 to lock bartworks to only generate up to UV to prevent issues in the future.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8536
=> Added recipe generation for cable diodes UHV and above

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
change sodium alunite recipe gives always 64 items per craft change red mud amount per craft
change red mud recipe from 10k to 1K
add the sodium alumitae mixer recipes to  chem reactor recipes (pure variants)
=> remove pure alu to sodium alunite recipes

.gitignore, src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
This changes all JABBA upgrade recipes in the Assembler to 13 to avoid conflicts.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11326
=> Change JABBA circuits to 13

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Problems:
1. MV cooling is a pretty bad mandatory time sink. I think the bit of complexity is very nice (ic2 coolant, potentially cooling the hot coolant back down). And some difficulty here makes the progression to the vac freezer feel good. But currently the time sink is over the top imo. It literally takes 2 hours of cooling (with one machine) to upgrade one EBF to kanthal. Then ofc there is Silicon and potentially Tantalum cooling. Kanthal cooling being annoying and over the top is the most common feedback from all players that have recently played MV.
2. The 75% loss of coolant is pretty extreme compared to other lossy processes. If you lose so much there is no incentive to try to invest in the recovery process.
3. its unclear why the cooling times for the 4 ingots should be so …
=> Make MV cooling lossless on coolant

src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java
Xenoxene as now is 300s at UEV, slowing the whole radox line to ground and it's honestly annoying to send that much energy into a culture that is already really dumb rng based to get slowed by it
=> change 300s to 180s

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
added assembler recipes for these as they are used in high tier t.f.f.t cells and were only craftable in a slice'n'splice
=> Add assembler recipes for totemic capacitor and skeletal contractor

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Adds recipes for the nei planet blocks as they are used in EOH recipe selection
They are tiered to fit their corresponding rocket tier and can be crafted after visiting their respective planets
Example:
=> Add recipes to the nei planet blocks

src/main/java/com/dreammaster/scripts/ScriptAvaritiaAddons.java
Fix one of the recipe conflicts in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12300 between compressed chest and obsidian chest.
also reduced the dense obsidian to be in line with the other recipes. Prompted by
new recipe:
=> Fix compressed chest conflict

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
adds dtpf recipes for chromatic glass to make mass production easier (for example for optical circuits)
The numbers follow the math of the other dtpf materials
=> Chromatic glass dtpf recipe

src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
I did a minor calculation mistake in the last pr, this fixes that
old values
new values
=> Fix catalyst amount for chromatic glass dtpf recipes

dependencies.gradle, src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
fixes the sifter method crash and adds contaminants to the grade 1 water recipe as chance outputs
=> Fix sifter crash + add chance outputs

src/main/java/com/dreammaster/gthandler/recipes/ForgeHammerRecipes.java
these recipes got lost somewhere along the way of merging things, so this pr re-adds them
=> Re-add missing forge hammer recipes for optical chips

src/main/java/com/dreammaster/gthandler/recipes/DistillationRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/LaserEngraverRecipes.java, src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
Adds small amounts of pollutant & misc outputs to the water line recipes to make them feel less empty.
Example(grade 7 water):
=> Add some more outputs to water line

src/main/java/com/dreammaster/gthandler/recipes/ExtruderRecipes.java
Adds extruder recipes for nether star pipes to move away from having to use the crafting recipe with tools
=> Add extruder recipes for nether star pipes

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Added high-tier 1 step recipe for Iridium Neutron Reflector.
This recipe changed to avoid unstackable items on recipes. With any bus except for stocking old recipes works very slow because of 1 recipe use ~4 slots. With super buses you cant use all parallel of your assembler for this craft.
=> Iridium Neutron Reflector recipes skip

src/main/java/com/dreammaster/gthandler/recipes/BlastFurnaceRecipes.java
- Corrected the appropriate recipes in order to set EBF temperature to 4000K, as intended by the last change.
See https://github.com/GTNewHorizons/GT5-Unofficial/pull/1628 for the PR that was originally meant to change this.
=> Fix for Tungstensteel Ingots Needing TPV Coils

src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
fixes a copy paste error in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/545 that resulted in recipes with no outputs, see https://discord.com/channels/181078474394566657/181078474394566657/1093927478021599372
fun fact: if you take 4 items to craft 1 of the same item, gt simplification nonsense subtracts the one and divides by 3.
=> Fix some ae recipes

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adds assembler recipes for new blocks added by Chisel. 
The recipes are LV tier and have a better efficiency, usually saving stone but sometimes other materials (e.g. factory block saves some iron)
Recipes are pretty much identical except iron ingots were replaced with iron plates
Also respects changes made to recipes in the modpack's zenscript like mossy temple block and energised voidstone
Depends on #559
=> Add Assembler recipes for Chisel blocks

src/main/java/com/dreammaster/gthandler/recipes/FluidExtractorRecipes.java
Fixes a small oversight in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/381.
A GaAr crystal is now worth 2 dust or ingots. That has to be the case for fluid extraction too.
=> AsGa fluid extraction fix

src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
Adds a new set of dptf recipes for some materials using the new stellar catalyst. These new recipes mostly follow the pattern of the already existing ones, except for the transcendent metal recipe which is new to the dtpf.
This new recipe combines all the materials needed for tesseract -> transcendent metal conversion and condenses them into a dtpf recipe. There is an added material in the form of cosmic neutronium blocks to give the recipe a bit of an additional cost and make it a tad more interesting.
The recipe:
Also adjusted the catalyst values in the infinity recipes as those had slightly wrong values
=> Add Stellar Catalyst DTPF recipes

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- this allows smd inductors in 16A diodes which adresses https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13250 on the coremod side. (needs bartworks fix for the lower tiers)
- instead of 2 separate recipes there is now only one with cycling ingredients as it should be. (also needs to be done in bartworks for lower tiers)
=> Oredicts diodes and inductors for 2A-16A diodes

src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
Adds chest recipes for GT++ Rainforest Oak and Pine logs to the assembler.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13429
=> Add vanilla chest assembler recipes for GT++ wood logs

src/main/java/com/dreammaster/gthandler/GT_Recipe_Remover.java
before:
```
[FML/]: Bar Step: PostInitialization - GregTech took 43.796s
```
after:
```
[DREAMCRAFT/dreamcraft]: Removed 2888 recipes!
[FML/]: Bar Step: PostInitialization - GregTech took 13.577s
```
=> Add buffering to recipe removals

src/main/java/com/dreammaster/gthandler/recipes/LatheRecipes.java
They were just giving null inputs in game and throwing errors in the normal log.
First I fixed them but then I realized they are already generated in GT itself in a much smarter and robust way (oredicts!). So they can just be deleted here.
Also removed some more duplicate recipes that are all covered in a smarter way by GT.
=> Remove broken duplicate recipes with forestry slabs and other duplicate slab recipes

src/main/java/com/dreammaster/gthandler/recipes/LaserEngraverRecipes.java
the lens isn't marked "NC" and gets consumed in the crafting
this fixes it
=> fix laser engraver consuming the lens

src/main/java/com/dreammaster/gthandler/GT_Loader_OreDictionary.java, src/main/java/com/dreammaster/gthandler/GT_Recipe_Remover.java, src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/FluidSolidifierRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/LaserEngraverRecipes.java
- fix desh ingot in recipe removals
- fix incorrect modloaded check for ic2classic item
- fix typo for bottle shape recipe and remove the duplicate recipe that was added after the one with the typo didnt work
- fix energized tesseract recipe
- fix endium unification
- fix amberblock unification
after my previous efforts to clean up the gt log, spotting these is now very easy :P
=> Recipe and unification fixes

src/main/java/com/dreammaster/gthandler/recipes/VacuumFreezerRecipes.java
follow up to https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/611. I missed one. Samarium also doesnt have a hot ingot.
=> Found one more broken vac freezer recipe

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
makes carton craftable by resolving a recipe conflict.
It does not seem to be used anywhere, but hey, at least its no longer broken:
and yes all you regular paperroll users will have to change the circuit, sorry.
=> Resolve paperroll/carton recipe conflict to make carton craftable

src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
- remove colliding duplicate recipes
- convert remaining recipes to RA2 and use tiereu and time units in existing RA2
- less usage of getmoditem for GT stuff
=> Cleanup ae2 script file

src/main/java/com/dreammaster/gthandler/GT_Loader_OreDictionary.java, src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java, src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
- add gem and crystal oredict to charged certus quartz item to generate sifting and autoclaving recipe.
- use the material in the oredict definitions to ensure its correct
- remove the manual autoclaving recipes from the script
- use the oredicts in the recipes
images combined with https://github.com/GTNewHorizons/GT5-Unofficial/pull/2013:
=> Charged certus quartz fixes

src/main/java/com/dreammaster/gthandler/GT_CustomLoader.java, src/main/java/com/dreammaster/scripts/ScriptBuildCraft.java, src/main/java/com/dreammaster/scripts/ScriptCoreMod.java, src/main/java/com/dreammaster/scripts/ScriptDraconicEvolution.java, src/main/java/com/dreammaster/scripts/ScriptEMT.java, src/main/java/com/dreammaster/scripts/ScriptLogisticPipes.java, src/main/java/com/dreammaster/scripts/ScriptThaumicTinkerer.java
- changes the load order in coremod. we need oredicts before the recipes. that fixes the PR circuit plate recipe.
- fixes thaumic restorer recipe (use oredict!)
- fixes BP pipe recipes (use oredict!)
- fixes shield focus recipes (use oredict!)
- fixes stone rod recipes (use oredict!)
- fixes draconic info tablet recipe (use oredict!)
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13506
(was caused by the script removal)
=> Recipe fixes for changed stone and glass

src/main/java/com/dreammaster/scripts/ScriptGregtechPlusPlus.java
The qft recipe for eternity was a bit too cheap, increased the cost by adding an energised tesseract and swapping raw stellar plasma with primordial matter
=> Eternity adjustment

src/main/java/com/dreammaster/gthandler/GT_CustomLoader.java
thus adding uhv-umv electromagnetic separators and microwaves.
In particular that should now make tengam craftable. Well assuming one get the ore.
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13518
=> fix broken wire definitions for uhv-umv machines

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11912 and https://discord.com/channels/181078474394566657/181078474394566657/1110363691628646460
adds the correct recycling for the iron and steam boiler tank. which also affects all machines that use these like the loco.
crucially it does not reintroduce any exploit. :)
=> Add correct recycling recipes for railcraft boiler tanks, steam loco, etc

src/main/java/com/dreammaster/gthandler/GT_CustomLoader.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13592. the pipe didnt exist. Also uses some more tier appropriate metals for the high tier extruders (nothing else seems to use these pipes).
=> Fix UIV extruder recipe

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
- add a _proper_ recipe for the hyperacceleration card. this was left "for later" here https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/471#issuecomment-1368061519
- 'fix' fluid amounts for alveary blocks in the new assembler recipes. They are now the same as in the old and still existing carpenter recipes. While the changed amounts might have been intentional, there was no mention of a balance change in the pr and no such discussion, nor does it make any sense to have different amounts in different machines. They were also inconsistent between the blocks, at least since https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/623.
helpful pic:
=> Two recipe improvements

src/main/java/com/dreammaster/scripts/ScriptEMT.java
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13611
In short, this brings the EMT Inventory and Armor Charging Rings down from EV to HV. Thus making them more comparible with other options like the nanosolarhelmet or LV solar(or other power) + LV wireless.
(was also brought to meta-dev with no disagreements sofar but some support)
new recipes as discussed in the ticket:
=> Improve EMT charging ring recipes

src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
This is meant to reduce the currently very high infinity cost of the T9 rocket, which was recently placed into UHV as mandatory progression, and remove metastable Og, which is technically possible in UHV, but requires a Mk4 fusion reactor (possibly a compact one depending on how much of a bottleneck it is for these crafts) which was agreed to be more of a UEV/UIV thing. These changes were agreed upon by the people in the discussion and glowredman. The discussion can be found at https://discord.com/channels/181078474394566657/401118216228831252/1117915558780874763
Mothership Navigation Console:
- 147456L Molten Infinity (1024 ingots) -> 14400L Molten Infinity (100 ingots)
- Replaced Molten Metastable Oganesson with Molten Enriched Naquadah Alloy
Rocket Engine Base:
- 73728L Molten Infinity …
=> Lower infinity costs and remove MS Og from T9 rocket

src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Adds the 1-step lapo battery recipes to the space assembler to reduce assline strain and fix the issue of the ultimate battery 1-step recipe not working because of research station collision.
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13052
=> Add 1-step lapo recipes to space assembler

src/main/java/com/dreammaster/gthandler/recipes/BendingMachineRecipes.java, src/main/java/com/dreammaster/scripts/ScriptCoreMod.java, src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java, src/main/java/com/dreammaster/scripts/ScriptGregtech.java, src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
- moves all the bending recipes from scripts to the bending file
- remove duplicate recipes that never were in the game as they were replaced by the automatically generated one
- readded important circuits to recipes that got lost when script files were moved to code
- replaced ids with oredictunificator
- **added one new recipe**: 9 obsidian ingot -> 1 dense plate (it was always the only material that didnt have this)
- use tiereu and seconds/minutes
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13693
=> coremod bending recipe cleanup

src/main/java/com/dreammaster/gthandler/recipes/BlastFurnaceRecipes.java
- anchors some recipes on argon instead of radon with a time such that the resulting smelting time with radon is (almost) the same. see https://github.com/GTNewHorizons/bartworks/pull/336 for all details.
- use TierEU for some recipes that werent using it.
=> adjust ebf recipes

src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java, src/main/java/com/dreammaster/scripts/ScriptEMT.java, src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13752
It was just a mix up of 'chance', 'time', and 'eu/t' when converting from scripts. sand for molten glass, poison from bop, and honey block from bop. The obsidian fluid extraction isnt fixed but removed as it never appears ingame anyway. It has a automatically generated recipe.
=> Fixes molten glass and other fluid extraction recipes

src/main/java/com/dreammaster/scripts/ScriptLogisticPipes.java
Fixes the following:
Also refactors the LP recipes to use constants for power usage and duration.
=> Fix oredict problems in LP recipes

src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
This allows the lappack and quantumsuit to have arbitrary charge level for the craft. The output of course still has 0EU charge.
The nbt seems to be ignored, so charge is just checked of the meta. wildcard lets us allow any. 
tested successfully with
=> Allow arbitrary charge level for GraviChestPlate inputs

src/main/java/com/dreammaster/scripts/ScriptHardcoreEnderExpansion.java
was caused by the script conversion. Fluid inputs and outputs were reversed.
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13843
=> Fix centrifuging recipes for endergoo and end powder

src/main/java/com/dreammaster/gthandler/recipes/ElectrolyzerRecipes.java
Follow-up to https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/562 specifically for clay.
With this PR Clay electrolysis gets chem balance, a slightly more realistic composition, and no more cheap hydrogen. But it keeps the alumina that was desired when the change was made in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/562.
New formula is 16 Na2LiAl2Si2O7(H2O)2 -> 2Na + Li + 5 Al2O3 + 6 SiO2 + 2000L H2O.
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13862
goes together with https://github.com/GTNewHorizons/GT5-Unofficial/pull/2114
=> New clay electrolysis recipe

src/main/java/com/dreammaster/bartworksHandler/VoidMinerLoader.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13687
technically buffs the DD void miner as drops are relative to total weight.
=> Remove non-existent ores from DD voidminer

src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
Adds conversion recipe for time to space and vice versa.
Molten space and molten time are sourced from the same recipe which yields both, and a lot of times one ends up with too much of either one. Plus the eternity qft recipe yields excess molten time which just sits there because you also get it when crafting molten space. This is especially noticeable very late into the game when primordial matter becomes a relevant crafting ingredient and molten space usage becomes higher than molten time usage.
These recipes aim to address these issues by adding a way to convert the two fluids into one another.
Time to Space:
Space to Time:
=> Time <-> Space conversion recipes

src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
Gives nether star dust a use and alleviates some of the extreme endgame need for nether stars/plates
=> Add compressor recipe for nether star block from dust

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Converts all of the assembler recipes for the NEI Ore Plugin dimension blocks to RA2.
All checks are also put behind applicable `isModEnabled` checks. If `GalaxySpace` is available then it is assumed `GalacticraftCore` and `GalacticraftMars` are available.
=> Convert NEI Planet Recipes to RA2

src/main/java/com/dreammaster/scripts/ScriptExtraTrees.java
these items were removed from binnies 6 years ago!! (https://github.com/GTNewHorizons/Binnie/commit/fe56638f16dcb093e97deb78bc1221bf3b824337)
about time we remove the attached broken recipes.
cleans up this broken beauty
=> Remove broken recipes from extra trees

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Left the existing tiny dust recipes so as not to break players' existing patterns, but we should be using full dusts wherever possible these days
=> Add normal dust recipes for OC cables

src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java
2 things actually:
- fixes the weird oxygen amounts that newly crafted higher tier tanks have. This was caused by https://github.com/GTNewHorizons/Galacticraft/pull/20
- makes the infinite oxygen tank recipe take _any_ ultra heavy tanks (instead of only full). This part is a buff, hence the _affects balance_ label
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13927.
=> Fix Oxygen Tank recipe and make the infinite oxy tank recipe more flexible

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
As most players in IV+ know, you cant just make a pattern for the EV lapo from nei, as then the result wont be recognized but you have to do it manually. This is in fact caused by a small mistake in the recipe.
the recipe is defined without a meta value which defaults to null and actually crafting in the game one gets an item with negative durability (it fixes itself when used but wont be recognized by a normal automation)
it also shows incorrectly as full in NEI:
With this fix instead one gets the correct meta value of 26 corresponding to an empty crystal (durability 1): 
it also shows correctly in NEI:
But not just that, I tested the interaction with NEI and AE2: using the ? to define a pattern from NEI does in fact now work without any adjustments!
=> Fix meta data for EV Lapotron Crystal recipe

src/main/java/com/dreammaster/coremod/DownloadProgressDialog.java
… when installed from CurseForge
=> Fix modpack name in the dialog that downloads mods on first startup… 

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Changes the recipe for the tier 4 ore drill to use europium frames as opposed to tritanium. The frames for void miner will be changed to instead use tritanium frames for its recipe. The gate for the void miner is the exact same so it won't affect balance.
This allows the last ore drill to see at least a bit of use before void miners are available, as opposed to being primarily a crafting component.
Should be merged with: https://github.com/GTNewHorizons/bartworks/pull/341
Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13979
=> Swap Void Miner and T4 MBM recipe frames

src/main/java/com/dreammaster/scripts/ScriptRailcraft.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14020 by just removing the centrifuge recipe. There is a working block->coal coke recipe in the forge hammer, which is the right place for this (e.g. same as normal coal). And that one has the right ratio.
Also cleaned up some duration and eut values from magic numbers to TierEU and SECONDS/MINUTES.
=> Coal Coke fix

src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java, src/main/java/com/dreammaster/scripts/ScriptAvaritia.java, src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java, src/main/java/com/dreammaster/scripts/ScriptBloodArsenal.java, src/main/java/com/dreammaster/scripts/ScriptBloodMagic.java, src/main/java/com/dreammaster/scripts/ScriptCoreMod.java, src/main/java/com/dreammaster/scripts/ScriptExtraUtilities.java, src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java, src/main/java/com/dreammaster/scripts/ScriptHardcoreEnderExpansion.java, src/main/java/com/dreammaster/scripts/ScriptHarvestcraft.java, src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java, src/main/java/com/dreammaster/scripts/ScriptProjectRed.java, src/main/java/com/dreammaster/scripts/ScriptRailcraft.java, src/main/java/com/dreammaster/scripts/ScriptStevesCarts.java, src/main/java/com/dreammaster/scripts/ScriptThaumcraft.java, src/main/java/com/dreammaster/scripts/ScriptThaumicBases.java, src/main/java/com/dreammaster/scripts/ScriptThaumicTinkerer.java, src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java, src/main/java/com/dreammaster/scripts/ScriptTinkersDefence.java
- converts the recipes to RA2
- integrates recipes from scriptfiles
- fixes some ismodloaded checks
- deletes some duplicate recipes that are generated by GT anyway
- uses SECONDS for times
- use some submethods for better organization
- directly use GT and coremod items instead of using the item registry
=> RA2 conversions, Script Integrations and Cleanup for Compressor recipes

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
well more precisely, fix 8 and remove 2.
- fixed fluid inputs for nose cone, heavy nose cone, bedrockium ingot (assembler recipe), unstable ingot (assembler recipe), linked card, magnet strip card, and Interweb. for the 2 ingots the fluid was just removed for good as its been broken for 7 years and people are used to it.
- fixed solid input for DD planet recipe.
- removed the 2 recipes for Sodium Aluminate based on impure and pure Biotite as those dont exist. all the other recipes for Sodium Aluminate are of course still around including the one from regular Biotite.
Some of these might slightly affect balance. but they are intended this way and all look fine. (just to explain the tag)
All tested in full game.
=> Fix 10 recipes

src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Adds two higher tier optical CPU recipes akin to the optical memory.
These recipes aim to address space assembler speed issues and incentivise higher tier material usage.
First alternate recipe for uiv tier:
Second alternate recipe for umv tier:
=> More optical CPU recipes

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
The inputs were empty after the recent refactor. This was causing thausands of recipe conflicts naturally. (including in the NEI custom diagram debug)
Now works again:
=> Fix heavy rocket fin recipe

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adds assembler recipes for most of the stuff listed here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13570
Does however not add recipes for the upgrade cards and small interfaces.
Most of the blocks are on circuit 2 and the crafting components on circuit 3.
I didn't spot any recipe conflicts, but i might need glasses idk
<details>
<summary>Recipe pictures</summary>
Annihilation Core
Formation Core
ME Controller
Crafting Unit
Energy Cell
Dense Energy Cell
Dual Interface
Interface
IO Port
ME Chest
ME Drive
Quantum Ring
Spatial Pylon
Spatial IO Port
ME Void cell
Wireless Connector
Wireless Receiver
Fluid Housing
Adv Fluid Housing
Multi Fluid Housing
Adv Multi Fluid Housing
Forgot to take picture of molecular assembler :)
</details>
I also haven't got a clue if this is …
=> Add assembler recipes for more ae2 items 

src/main/java/com/dreammaster/gthandler/recipes/ElectrolyzerRecipes.java
In the previous PR about brick electrolyze recipe I made a mistake and put Silicon instead of SiliconDioxide. This should fix oxygen magically turning into silicon
=> fix mistake in brick electrolyze recipe

src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java
most of them are in gt itself, so do it there and remove the one here.
Needs to be merged together with https://github.com/GTNewHorizons/GT5-Unofficial/pull/2210. See details there.
=> Fix and clean up ammonia recipes

src/main/java/com/dreammaster/scripts/ScriptEMT.java
Fixes this recipe:
now shows correctly:
=> Fix one TC recipe

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
I was told that Quadruple Input Hatches can be crafted in previous tiers, because the assembler recipes are all LV. This PR fixes that, to have them match the regular Input Hatches in the recipe tiers. 
Coremod has the UEV to UXV ones, including the Humongous Quad Hatch, so the changes here are for those. [See this PR for the other hatch tiers.](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2211)
=> Adjust Recipe Tiers for Endgame Quad Input Hatches

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
was broken by transform to RA2:
now fixed:
=> Fix fences for piston assembler recipes

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
now works with a sapling dropped from a tree:
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14163
=> Fix wrong meta for barnada C sapling

src/main/java/com/dreammaster/gthandler/recipes/ImplosionCompressorRecipes.java
was another ra2 conversion error. fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14165
recipes now:
=> fix compressed dual desh plates

src/main/java/com/dreammaster/scripts/ScriptGregtech.java
we dont use rotarycraft, so we dont use HSLA, so this recipe is just broken:
2 PRs because the recipe was added twice. The other is https://github.com/GTNewHorizons/GT5-Unofficial/pull/2241
=> Remove broken HSLA recipe

src/main/java/com/dreammaster/scripts/ScriptAutomagy.java
Just had the incorrect text (for years). Now fixed:
=> Fix amber light research text

src/main/java/com/dreammaster/galacticgreg/SpaceDimRegisterer.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14008 and GT ores completely missing in the Mehen Belt dimension.
=> Fix wrong Mehen Belt ChunkProvider class

src/main/java/com/dreammaster/scripts/ScriptEMT.java
Apprently the GT drills got buffed for whatever reason and use like 2 tier cheaper materials now. well this part was forgotten.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14267
=> Fix EMT thaumium drill crafting

src/main/java/com/dreammaster/scripts/ScriptGregtechPlusPlus.java
the proper recipe is now fixed, so we dont need this placeholder one anymore.
only merge after https://github.com/GTNewHorizons/GTplusplus/pull/746
=> Remove duplicate cloaking device placeholder recipe

src/main/java/com/dreammaster/scripts/ScriptDraconicEvolution.java
The draconic chestplate recipe had 2 draconic energy cores and 1 awakened core in its recipe while all other wyvern and draconic armor parts have 1 energy core and 2 cores
This PR swaps the draconic energy cores and awakened cores in the draconic chestplate recipe to make it consistent with the other armor pieces.
Draconic chestplate recipe pre-fix:
Wyvern chestplate recipe (as an example for 2 cores, 1 energy core):
This technically affects balance but in an extremely minor way with basically no consequences.
=> Fix draconic chestplate recipe inconsistency

src/main/java/com/dreammaster/scripts/ScriptThaumcraft.java
Effectively, our in-pack lore of the essentia mirror and magic mirror is that the magic mirror is supposed to be one tier higher than the essentia mirror, the magic mirror was originally IV, while the essentia mirror was EV, then the magic mirror was buffed in late 2021:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/69d5f23c8afa8e838640e66e7ab91e7e1ccf862f
However, when Piky upgraded the magic mirror from IV to HV back in 2021, he forgot to also buff the essentia mirror from EV to MV respectively, as to fit within our own lore, and this has been bugging me ever since.
No, most reasonable players will not be able to unlock this until HV, since infusion is currently HV, so it's effectively HV anyway, but for consistency's sake, this change needs to happen.
=> Buff Essentia mirror to maintain consistency with the lore

src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
fixes point 3 in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14596
only assembler recipes now:
where the steel item casing is oredicted. first is basic, second silver capacitor.
=> Fix and cleanup machine chassis recipes

src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
Adds receipts for items from this [AE2FluidCraft-Rework#162](https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/162)
Related to proposal: Close [GT-New-Horizons-Modpack#14554](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14554)
Final recipe
© UpSideDown
=> Add recipe `LevelTerminal` `LevelWireless`, mod `ae2fc`

dependencies.gradle, src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
This adds the new recipes for the different kind of stocking buses/hatches that got added. There are now two kinds of each type one that has the autopull functionality and one that does not. This was implemented in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2349
They are gated like this:
```
- Stocking Input Bus (ME) without autpull EV
- Advanced Stocking Input Bus (ME) with autopull LuV
- Stocking Input Hatch (ME) without autopull UV
- Advanced Stocking Input Hatch (ME) with autopull UEV
```
- 1 Input Bus (HV)
- 1 ME Interface (This was changed into the full block to avoid one additional crafting step)
- 4 Acceleration Card
- 1 Programmed Circuit 1
- 1 Input Bus (LuV)
- 1 ME Interface
- 1 Conveyor Module (IV)
- 4 Acceleration Card
- 4 Quadruple Input Hatch (UV)
- 1 ME Dual …
=> Add recipes for stocking buses/hatches

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adds a maintenance hatch recipe with advanced glue (refined glue and super glue both have one already). This recipe is the same as the one with refined glue but uses less glue and has a different circuit:
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14872.
=> Add maintenance hatch recipe with advanced glue

src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Fix an oversight with the crafting input bus. Now bot the assembly line recipe and the scanner need the advanced version of the stocking bus
=> Fix the recipe and the research for the crafting input bus

src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Adds a space assembler recipe for lapotronic energy orb clusters to keep it consistent with the other energy orbs and to make faster than 1 tick production of these possible.
=> Add lapotronic energy orb cluster space assembler recipe

src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
All these recipes are already auto-removed (as collisions) in all the recent stables. They are no longer needed since circuit components got GT oredicts. So it is best to remove them directly from the code.
Also cleaned up the order and comments slightly.
I checked the recipes with this PR in a full game and they all look fine.
This is related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14935 but not the main issue there.
=> Remove duplicate circuit recipes from code

src/main/java/com/dreammaster/scripts/ScriptChisel.java
as the title says. This fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14941 and one part of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11750
=> Add blaze blocks to chisel

src/main/java/com/dreammaster/recipes/RecipeRemover.java
There is such output stack whose getItem returns null
=> Recipe remove NPE

src/main/java/com/dreammaster/amazingtrophies/AchievementHandler.java, src/main/java/com/dreammaster/main/MainRegistry.java
Depends on https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15071.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15070.
=> Handle Unbreakable TCon Tool Achievement via Code

src/main/java/com/dreammaster/scripts/ScriptLogisticPipes.java
Fixes https://discord.com/channels/181078474394566657/401118216228831252/1187451434690678827
Fixes https://discord.com/channels/181078474394566657/401118216228831252/1187456065202294885
Caused by the usual suspects. one by https://github.com/GTNewHorizons/GTplusplus/pull/767 and one by https://github.com/GTNewHorizons/GTplusplus/pull/729
I replace the ulv parts by lv. best I can do.
Now working: 
(just the 2 recipes)
=> Fix a few broken LP recipes using gt++ items

src/main/java/com/dreammaster/amazingtrophies/AchievementHandler.java
Partially fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15217. The infinity sword only deals 4 points of damage when hitting a player in full infinity armor (see <https://github.com/GTNewHorizons/Avaritia/blob/master/src/main/java/fox/spiteful/avaritia/items/tools/ItemSwordInfinity.java#L57-L84>).
=> Add Special Handling for the Infinity Sword

src/main/java/com/dreammaster/scripts/ScriptChisel.java
adds four more blocks to basalt chisel group.
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14488
=> Add more basalt blocks to chisel

addon.gradle, dependencies.gradle, src/main/java/com/dreammaster/coremod/transformers/ItemFocusWardingTransformer.java, src/main/java/com/dreammaster/main/MainRegistry.java, src/main/java/com/dreammaster/mantle/BookDataReader.java, src/main/java/com/dreammaster/mantle/BookDataStoreProxy.java, src/main/java/com/dreammaster/mantle/BookLoader.java, src/main/java/com/dreammaster/mantle/MantleBookLoader.java, src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java, src/main/resources/assets/dreamcraft/tinker/manuals/diary.xml, src/main/resources/assets/dreamcraft/tinker/manuals/firstday.xml, src/main/resources/assets/dreamcraft/tinker/manuals/materials.xml, src/main/resources/assets/dreamcraft/tinker/manuals/smeltery.xml, src/main/resources/assets/dreamcraft/tinker/manuals/weaponry.xml, src/test/java/com/dreammaster/mantle/BookDataReaderTest.java, src/test/java/com/dreammaster/mantle/BookDataStoreProxyTest.java, src/test/java/com/dreammaster/mantle/MantleBookLoaderTest.java, src/test/resources/assets/dreamcraft/mantle/test-book.xml
This PR is unfinished  pending the inclusion the required lang file keys to allow for translation.
Actual customization might happen in a different PR, or in this one.  More is done but it is not yet cleaned up for review. In the current state the en-US books are kept as is to serve as a base on which to compare the content changes.
=> Allow customizing  Tinker's Construct manuals in dreamcraft

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
In response to: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13921
I rewrote the Ztones recipes to better allow for additional ingredients to be usable in assembling. 
This is my first PR for GregTech: New Horizons - my friends and I encountered this issue in our own playthrough, so I gave it a go at fixing.
=> Add Non-Vanilla Dye Support to ZTones Blocks within Assembler

gradle.properties, settings.gradle, src/main/java/com/dreammaster/item/WoodenBrickForm.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15495.
And brings the form in line with other gt tools with durability none of which are stackable.
Also makes the mod build again as the BS was broken.
=> Wooden brick form fix

src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
tinkers molten lead is completely useless. Being able to obtain it is just a noob trap and confuses people.
This PR removes the recipes to obtain it. Will add a WG PR as well.
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15422
=> Remove lead from smeltery

src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
The ratios based on all other recipes are
1 glass bottle = 1 glass dust = 144L GT molten glass = 1000L tinker molten glass.
This one recipe did not follow that, hence the fix. Without the fix one can loop for infinite glass.
=> fix glass bottle exploit

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Update the assembler recipe for Tinted Glass to match the other ZTones blocks.
This fixes [#9167](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9167), which was left as stale.
=> Update Tinted Glass assembler recipe

src/main/java/com/dreammaster/scripts/ScriptHarvestcraft.java
The current cutting board recipe (just stainless steel butchery knife shapeless) is broken in 2 ways:
1) it actually allows any material, not just stainless steel (older bug, see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4234#issuecomment-471341785 not sure if it worked in between with that fix there.)
2) it only uses a bit of durability instead of the full tool (newer bug)
Fixing it seems tricky and not really worth it. Instead I just took the stainless steel butchery knife recipe and added the wooden plank as differentiation and because it fits:
fixes https://discord.com/channels/181078474394566657/181078474394566657/1206595468683903077
=> new cuttingboard recipe

src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15611
in more detail:
- changes recipes for the copying of moon buggy/astro miner/cargo rocket schematic to be the same as the equivalent rocket tier schematic it can be exchanged with
- add programmed circuits to the recipes. otherwise they are removed as duplicates! the nbt on the datastick doesnt count. :(
- use oredict for circuits for all these recipes so that the circuits cycle in NEI instead of having 12 separate recipes for the different circuits.
=> Fix moon buggy copy recipe and related fixes

src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java, src/main/java/com/dreammaster/scripts/ScriptTinkersDefence.java
fix incorrect item names in 5 tinkers defence recipes.
fixes the last few point and thus closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15676
=> Fix broken tinkers defence recipes

src/main/java/com/dreammaster/scripts/ScriptAvaritiaAddons.java
Better integration for https://github.com/GTNewHorizons/ironchest/pull/16.
Uses dark steel chests for compressed chests, to integrate them more properly in the progression.
Specifically, compressed chest recipes are now:
note, that this now even has correct math for slots. 108 (obsidian) + 135 (dark steel) = 243 (compressed).
=> More dark steel chests recipe tweaks

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Removes the redundant recipe (that uses itemlist to suppress unification) as the other is unified anyway. Made that one a bit more clear with GT_OreDictUnificator but that is just cosmetics.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15911
=> Remove duplicate TF portal gen recipe

dependencies.gradle, src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
This PR fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14627 by adding the missing recipes (TC slime items + Lignite)
Marked as draft since commit 6579f42d2539cc3082ffab110fe2519ff3d1f9fe (simplify recipes by using the oredict for `slimeball`) does not work.
Is it intended that using the oredict for input items does not work? In the recipe for `iron_bars`, `stickAnyIron` (`OrePrefixes.stick, Materials.AnyIron`) is used, which is also ignored and simplified to only the default `iron rod`
Ifit is not intended to use oredict names for input items, we can revert the last commit and un-draft.
=> Add missing resistor recipes

src/main/java/com/dreammaster/scripts/ScriptChisel.java
Fixes one aspect of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16045 which might be all it needs, not sure.
In particular, this means you can compress 9 end stone dust to a block (that you can chisel to all the variants).
=> Add missing endstone variant to chisel

src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java
Restore missing recipes as assembler recipes.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13982
=> fix: Restore walkway recipes that were dropped in 2.3.0

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/scripts/ScriptGregtech.java, src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
This PR adds assembler recipes for a few items that are used in large volumes.
AE2 related stuff:
- AE2 basic and advanced card
- Advanced blocking card
- Pattern capacity card
- Acceleration card
- Hyper-Acceleration card
- Flat ME interface (this uses the same recipe as a regular interface but with a different circuit number, as suggested in GTNewHorizons/GT-New-Horizons-Modpack#15276)
DTPF casings:
- Super Chest V
- Super Tank V
- IV Chest Buffer
- UV Microwave Transmitter
Yottank cells/EOH parts
- UV compressor
Dyson related stuff (by @C0bra5)
- IC2 Advanced Machine Casing
- IC2 Stirling Generator
- IC2 Heat Component
Various
- EV bending machine (used by bending machine multi) by @C0bra5
=> Add a few missing assembler recipes for large-volume items.

dependencies.gradle, src/main/java/com/dreammaster/scripts/ScriptProjectRed.java
In https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/840, Project Red Transportation has been downtiered and many recipes changed. However, in this PR, recipes for several PR parts have been completely removed: Silicon, Red Silicon Compound, Infused Silicon, and Silicon Chip. These recipes make up a crafting chain, and the Silicon Chip is used to craft several PR logic gates, which are unobtainable otherwise. This PR restores the four removed recipes.
We talked about this with @chochem on discord, and I believe this removal was accidental, as I see no reason for it. I suspect @Dream-Master simply did not notice that the chips have other uses than logistic pipes and thought them redundant. If there is any legitimate reason to remove these recipes, then an alternate way of crafting …
=> Restore (accidentally?) removed ProjectRed recipes.

src/main/java/com/dreammaster/scripts/ScriptAvaritiaAddons.java
As discussed in meta dev and proposed in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16297, this PR increases the amount of attempts for the start of the eternity loop from 2 -> 5 by decreasing the required amount of timepieces from 2 -> 1 and proportionally decreasing the mhdcsm input from 576 -> 288L as well. 
This brings the chance of complete failure down to less than 0.1%, without even accounting for the extra timepieces one can get from those 5 tries, which allow for more tries.
=> Improve chronic singularity recipe

src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Downtiers the uev gate parts to uiv to make them actually craftable in uev (umv hatches cant be obtained in uev anymore like they used to back then)
=> Fix trophy item voltages

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
In #827, I added assembler recipes for a few large volume items, but accidentally used an IV Super Buffer instead of IV Chest Buffer for Super Chest V. This is especially unhelpful because the Super Buffer does not have an assembler recipe, making the fix entirely useless :)
This PR changes the recipe back to a Chest Buffer
=> Fix accidental nerf to super chest V recipe

src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
This PR adds DTPF recipes for superconductor base LuV and ZPM and a higher tier version of the quantum anomaly recipe.
Both superconductor bases get 4 recipes, from crude to exotic (analogous to the other superconductor recipes), with the difference of SC base LuV requiring oxygen plasma instead of oxygen gas (with a 32x discount).
The new quantum anomaly recipe is twice as fast as the old one, but is recursive and both uses the harder to get graviton (incentivising the particle acceleration qft recipe) and tritanium instead of duranium.
Quantum Anomaly:
Base ZPM:
Base LuV:
=> Add SC Base LuV & ZPM and better quantum anomaly DTPF recipe

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Fix the flat AE2 interface assembler recipe costing 1 more annihilation core than it should.
=> Fix flat interface assembler recipe

src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Fixes the sg plates being used in 2 researches each (leading to conflicts)
=> Fix sg trophy research conflicts 

src/main/java/com/dreammaster/gthandler/DTPFCalculator.java, src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java, src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java, src/main/java/com/dreammaster/main/MainRegistry.java
As the title suggests, this PR adds a calculator to help with the creation of dtpf recipes. 
Until now one had to use a complex spreadsheet without much documentation to determine the parameters for each recipe, which wasnt great for maintainability.
The DTPF calculator replaces that by implementing all the necessary math into a documented and consistent tool in code.
Recipes for materials can be either generated directly based on their ebf and vacuum freezer recipes or based on a manual input of recipe voltage and duration (useful for materials that dont have ebf & vacuum freezer recipes, like chromatic glass).
This has the side effect of a large portion of dtpf recipes changing, as now both the ebf gas changes that happened a year ago have been taken into account by the calculator and …
=> Add calculator for DTPF recipes

src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java, src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
follow up to https://github.com/GTNewHorizons/GT5-Unofficial/pull/2687 so that coremod works again.
=> Remove gtcrate recipes from scripts

src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
The nt frame box is already used in space elevator research
=> Fix neutronium frame box research conflict

src/main/java/com/dreammaster/scripts/ScriptIronChests.java
2 Dense Plates needed per chest, no matter if you use the upgrade item or craft the chest in the assembler.
=> Standardize the Obsidian Amount needed for the Obsidian Chest

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adds shapeless recipes to craft the ME output bus and hatch with AE storage components to change the base cache size. Requires https://github.com/GTNewHorizons/GT5-Unofficial/pull/2718 to actually do anything useful.
=> Add recipes to pre-apply storage components to ME hatches

src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
Based on my question https://discord.com/channels/181078474394566657/401118216228831252/1261395316830376037
Removes remaining recipes for backbone cables, they are deprecated since 2.4, last 6 recipes likely forgotten by
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/694 removal.
Compiled mod was tested in full pack (latest nightly), and recipes been successfully removed.
=> Remove remaining recipes for backbone cables

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
Currently, the AE2FC advanced fluid storage housing items require Neutronium for the single fluid type, and Infinity for the multi-fluid type. This creates a situation where the player can make storage components for higher-capacity fluid disks fairly early, but can't actually put them in ME Drives and ME Chests due to the stringent housing requirements. Additionally, with the ME output hatch change, these storage components can be employed to buffer fluid up to their capacity in an ME output hatch as early as EV. Combined with a smaller disk with a sticky card somewhere else in the network, this allows the components to be used (after a fashion) without incurring the cost of the housing.
In light of this, I've authored this PR. It changes the recipes for these items to use GT++ alloys. I …
=> Downtiers advanced fluid storage housings

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
PR pre-adding the recipes used in these PRs:
https://github.com/GTNewHorizons/GT5-Unofficial/pull/2729
https://github.com/GTNewHorizons/GT5-Unofficial/pull/2726
Specifically:
-TurboCan Pro
-Magnetic Flux Exhibitor
-Electromagnet Housing
-MagTech Casing
-Iron Electromagnet
-Steel Electromagnet
-Neodymium Electromagnet
-Samarium Electromagnet
-Tengam Electromagnet
=> Add recipes for MFE and TurboCan

src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Related PR https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/529
Tiers the cell to UXV, requiring a full UMV battery. Expensive, but primarily intended for niche setups and possibly as an ingredient for Stargate parts later on. Shouldn't become the primary item storage option due to the cost, but we'll see.
=> Add recipe for Artificial Universe Cell

src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/ExtractorRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
This PR adds a new recipes to the avaritia star fuel item and amun ra dark matter, both of which are planned to be used in the upcoming godforge multiblock. Dark matter can be found naturally generating on the mehen belt, these recipes are optional ones for those who dont want to go search for it in world.
=> Add new recipes to star fuel and dark matter

src/main/java/com/dreammaster/gthandler/multiAirFilter/GT_MetaTileEntity_AirFilterBase.java
Random.nextInt(int) is already exclusive on the upper end, so the -1 actually causes precisely one chunk to be ignored.
=> Fix off-by-one error in chunk randomization

src/main/java/com/dreammaster/baubles/OvenGlove.java
Added check for if the game is currently in Peaceful, and if so, to cancel the damage event pre-emptively.
For reason, see [Issue #16879](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16879)
=> Fix for Issue #16879

dependencies.gradle, src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
Requires https://github.com/GTNewHorizons/GT5-Unofficial/pull/2792
Adds shapeless recipes to craft EOH controller with planet block. A planet block will be added to controller slot when placing the controller.
=> Add recipes to pre-add planet block to EOH controller

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/FluidSolidifierRecipes.java
Adds all missing recipes for waterline hatches and T8 casings.
*pH Sensor Hatch*
*Lens Housing*
*Lens Indicator Hatch*
*Degasser Control Hatch*
*Absolute Baryonic Perfection Purification Unit (screenshot missing molten superconductor base UHV)*
*Quark Exclusion Casing*
*Femtometer-Calibrated Particle Beam Casing*
*Particle Beam Guidance Casing*
*Non-Photonic Matter Exclusion Glass*
=> Final recipes for waterline

src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Recipes existed fine, but would not run properly, this fixes them so the controllers are properly craftable with oredicted circuits.
=> Fix waterline recipes not running with any circuit other than the any circuit item

src/main/java/com/dreammaster/scripts/ScriptCatWalk.java
fixes infinite steel exploit, fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17021, and turns the recipes into proper recycling recipes.
=> fix catwalks recycling recipes

src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java
the toolHeadArrow was removed so this recipe was broken. now uses the corresponding tinker arrow head. (and a spring because thats how it works :P )
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17018
=> fix grapple recipe

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
We were previously trying to generate recipes for every ZTones block that uses dye with every oredicted dye variant. This did not actually work, and caused broken recipes that looked like this (and about a thousand recipe collisions):
I have made it not try to use oredicted dye and just use the GT dye instead, since actually trying to fix the oredicting would just be adding thousands of bloated recipes to assembler.
=> Remove one thousand (!) ztones collisions

src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
This PR adds the dyson swarm assline recipes in coremod, moving them from galaxyspace.
related PR:https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/115
=> Move dyson recipes to coremod

src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
Quicksilver singularity was broken because there is no properly gt-oredicted quicksilver block. Just made it cost 9x the amount in cinnabar dust instead.
=> Fix quicksilver singularity

dependencies.gradle, src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java, src/main/java/com/dreammaster/gthandler/CoreMod_PCBFactory_MaterialLoader.java, src/main/java/com/dreammaster/gthandler/GT_CoreModSupport.java, src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/LatheRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java, src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
Depends on https://github.com/GTNewHorizons/GT5-Unofficial/pull/3001 to access the radox materials in the GT5u `Materials` enum.
=> Move radox to GT5u

src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
This PR makes the second dtpf quantum anomaly recipe faster so its more worthwhile to use compared to the lower tier one.
=> Increase speed of second dtpf quantum anomaly recipe

src/main/java/com/dreammaster/scripts/ScriptLogisticPipes.java
Previously recipe was made for forming press, which is supposed to be LV tier. But since it requires 3 ingredients, its craft requires HV version. This commit transfers Active Supplier Module recipe from Forming Press to Assembler to allow its craft on LV tier.
The module itself is very simple, so old recipe was my mistake
=> fix: migrate module recipe from forming press to assembler

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Large Fluid Extractor (EV tiered):
Each solenoid tier made in an AL needs the previous tier as its research item.
MV Solenoid:
HV Solenoid:
EV Solenoid:
IV Solenoid:
LuV Solenoid:
ZPM Solenoid:
UV Solenoid:
UHV Solenoid:
UEV Solenoid:
UIV Solenoid:
UMV Solenoid:
=> Added large fluid extractor & solenoid recipes

src/main/java/com/dreammaster/main/MainRegistry.java
Makes it so the buckets aren't null when used in recipes
=> move ItemBucketList registration to postload

src/main/java/com/dreammaster/scripts/ScriptSGCraft.java
I want to add a recipe for this block, but I'm not sure if it's appropriate.
https://github.com/GTNewHorizons/SGCraft/pull/19
=> add stargateController recipe

dependencies.gradle, src/main/java/com/dreammaster/gthandler/recipes/CentrifugeRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/VacuumFurnaceRecipes.java, src/main/java/com/dreammaster/recipes/RecipeRemover.java, src/main/java/com/dreammaster/scripts/ScriptGregtechPlusPlus.java
a third follow up to https://github.com/GTNewHorizons/GT5-Unofficial/pull/3140 removing hidden forestry deps.
the gtpp reciperemovals are no longer needed due to https://github.com/GTNewHorizons/GT5-Unofficial/pull/3146
=> add missing ismodloaded checks for forestry

dependencies.gradle, src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
Properly use metadata for neutronium compressor recipes
=> Fix nei singularities

src/main/java/com/dreammaster/scripts/ScriptAdvancedBackpacks.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17159
This allows any pair of the night vision googles to be used in the recipe just like is allowed for the nano helmet
=> Fix bat backpack recipe

src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
Adds an alternate recipe for Eternal Singularities in the Black Hole Compressor, which requires a UXV hatch and runs 64 singularities for only 1/16th of the total time. Keeps the longer duration to encourage the machine's special mechanics. Uses a black hole opener in the recipe to offset some of the "cost" of not having run the original recipe, and to also challenge automation as this item is also used to automate the machine outside of recipe cost.
=> Add alternate recipe for Eternal Singularity

src/main/java/com/dreammaster/scripts/ScriptHarvestcraftNether.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17315.
apparently we want it to be 9:1 not full so the oredict needs to go as it makes a 1:1 recipe.
=> Fix inconsistent nether flesh recipes

src/main/java/com/dreammaster/gthandler/GT_Loader_OreDictionary.java
Railcraft items were removed but not their oredict entries, which caused "object "part.plate" with mod id "Railcraft" has returned null because the item was not found in the game registry" to be thrown in the log.
=> Remove railcraft oredict

src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
The alternate eternal singularity recipe caused a collision. Changes the input to eternity instead of spacetime, both removing the collision and making it more of a "better recipe unlock"
=> Change alternate eternal singularity recipe

src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
Nerfs the new eternal singularity alternate recipe to only do 1/4th of the singularities at a time from the previous iteration. Efficiency of Eternity -> Singularities remains the same, and this recipe is still 4x faster than the standard eternal singularity recipe (compared to 16x before)
=> Nerf eternal singularity alternate recipe

src/main/java/com/dreammaster/scripts/ScriptEMT.java, src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
makes in uncraftable and also replaces it in its one recipe usage.
Reason being that this is a gt pack and people just confuse it with the gt++ one constantly (as they search "semifluid" instead of "semi-fluid"/"semi fluid".
fixes https://discord.com/channels/181078474394566657/603348502637969419/1287196183185457252
new potentia gen recipe works:
=> Deprecate ic2 semifluid gen

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Related to https://github.com/GTNewHorizons/GT5-Unofficial/pull/3261
Again, hoping I can push this through since it's pretty egregious and related to beta feedback 🙏 
Reduces the incoloy-903 cost of the compressor casings by a lot, replacing some with titanium. Frankly, this multi is still very expensive at its tier. It was way way too much before and that's my fault for not really thinking about the EV cost when I was making these recipes.
Also made the stabilization casings for neutronium compressors give 4 (from 2) per recipe, since their cost is very high in field generators and the multi is already much more expensive than its original singleblock.
=> Buff compressor casings

src/main/java/com/dreammaster/coremod/DepLoader.java
this attempts to open the zip file (which itself should do some validation, but I'm not sure what they are) and checks each file in the downloaded jar against the builtin crc32 checksum 
I've verified that it will report error if a jar is truncated (very common if network is bad) and will not report any jar that comes with 2.6.1 as corrupted.
=> implement jar validation for deploader

src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java, src/main/java/com/dreammaster/scripts/ScriptAvaritiaAddons.java
Removes the new Eternal Singularity recipe. This was a bit of an experiment and after more consideration we don't think this is needed.
Also fixes a visual issue with the Spaghettic and Cryptic Singularities not mentioning that they need black hole
=> Remove new Eternal Singularity recipe, fix other singularities

src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
Recipe for lightweight plates needed itnt in the EIC because it had manually defined an amount of itnt in the recipe instead of using the metadata system that every other implosion recipe uses.
=> Fix EIC recipe using itnt

src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
The tier 8 waterline multiblock has proven itself to still be way too expensive, so this final buff removes the UEV field generator cost from the most used casing and replaces it with a UHV field generator instead to cut down on infinity.
=> Buff T8 waterline cost (again)

src/main/java/com/dreammaster/scripts/ScriptBloodMagic.java
The material was accidentally changed from mytryl to mysterious crystal (higher tier) by a getmoditem-refactor. This is the fix. back to the 2.6.1 and prior recipe.
=> fix ichorium block infusion recipe

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/scripts/ScriptEnderIO.java, src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java
Adds assembler recipes for:
- Galacticraft Oxygen Vent
- EnderIO Vibrant Capacitor Bank
- EV Battery Buffer (16 Slots)
- Bronze/Steel/Titanium/Tungstensteel Firebox Casings
- Alloy Blast Smelter controller
- IV Alloy Smelter
- LuV World Accelerator
- Assembler Machine Casing
These items are all things used at larger scale than previously due to the stargate recipe changes, or in the case of a few, desperately needed assembler recipes previously
=> Add assembler recipes for some new items used in stargate

src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/ImplosionCompressorRecipes.java
Rework agreed upon with @GDCloudstrike 
Due to changes to the compressor in 2.7, as well as the addition of Superdense Plates which strain the compressor much more (and, as a result, the Electric Implosion Compressor much less since singularities were also moved), we decided it would be a good idea to no longer have a Dust -> Block recipe for Nether Star Block, instead having a Dust -> Gem Electric Implosion Compressor recipe, and then doing the normal Gem -> Block compressor recipe.
Duration + EU/t are chosen based on the former recipe:
15s @ UV for 1 Block (9 Gems worth of Dust) -> 3.75s at UEV -> 1.25s at UEV for 3 Gems, so the total time is unchanged, but the process is moved to another machine and standardized more. Additionally, this does slightly increase the cost of Nether Stars …
=> Rework endgame nether star processing

src/main/java/com/dreammaster/gthandler/recipes/MaceratorRecipes.java
was accidentally removed when ic2 recipes were moved.
also doesn't autogen for some reason and never has but the debug for that was accidentally(?) removed as well, so who knows.
also of course the block shouldnt even generate but thats not a bug anyone has figured out so far. XD
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17610
=> readd iron ore gravel recipe

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adds recipes for the Item Holder covers added here: https://github.com/GTNewHorizons/GT5-Unofficial/pull/2593.
Follows the format:
`Tiered Chest (from Input/Output Bus recipe) + Tiered Plate + C1 + Tiered Fluid (from other cover recipes), 40s @ 16 EU/t (both from other cover recipes)`
I decided not to have the assembler recipes be tiered, and instead all LV, but I could go either way on this so I'm open to opinions.
I'm marking this as a bugfix PR since these covers were added in this dev cycle, and recipes were just forgotten about for a while, so I think this should definitely go into 2.7.
=> Add recipes for Item Holder Covers

src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java, src/main/java/com/dreammaster/scripts/ScriptAE2FC.java, src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java, src/main/java/com/dreammaster/scripts/ScriptThaumicEnergistics.java
Moves the digital singularity recipe to space assembler to reduce the strain from dire tables and to make it more consistent to Artificial Universe.
=> Move Digital Singularities from Dire table to Space Asssembler

src/main/java/com/dreammaster/main/MainRegistry.java
Currently the Ztones glass is insta break which makes it annoying to work with since you will constantly break some of it accidentally. Since it is insta break it will also often create ghost blocks. This pr sets the hardness of the block to be the same as vanilla glass.
=> Set hardness of the Ztones glass to be the same as normal glass

src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Wireless data currently has the same gating wireless computation, which is gated behind eternal DTPF, primarily because of dyson, but data doesn't have the same issue.
This downtiers the wireless data hatches to UEV, to help the assembly line scaling, for example crafting the DTPF, which usually makes the players setup a dozen of assembly lines.
=> Downtier wireless data hatches to UEV

src/main/java/com/dreammaster/thaumcraft/TCLoader.java
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.item.Item.getDamage(net.minecraft.item.ItemStack)" because the return value of "net.minecraft.item.ItemStack.func_77973_b()" is null
at Launch//net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
at Launch//com.dreammaster.thaumcraft.TCLoader.checkRecipeProblems(TCLoader.java:64)
at Launch//com.dreammaster.main.MainRegistry.CompleteLoad(MainRegistry.java:517)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at Launch//cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103 …
```
=> fix NPE in TCLoader

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adds previously missing lsc casing to the lsc recipe, previously allowing for a slightly cheaper assembler recipe for no reason.
=> Add lsc casing to lsc assembler recipe

src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
Removes the IC2 coolant cutting recipe for callisto ice plates from blocks. This already has a lubricant cutting recipe, and this recipe is just a remnant from the now removed cold callisto ice plate
=> Remove callisto ice ic2 coolant cutting recipe

src/main/java/com/dreammaster/gthandler/recipes/BlastFurnaceRecipes.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17784
While shadow steel does not conflict with shadow iron ingot, this is the only recipe which makes another item while fluids are stocked, so you either have to manually remove oxygen from MBFs, dedicating a MBF without oxygen, or autocrafting the gasses for it.
This changes the recipe to follow the carbon way of making steel for shadow steel, 4 shadow iron and 1 carbon makes 4 shadow steel
This PR does increase the voltage and coil requirement for it, but since shadow iron is a T5+ ore, this shouldn't affect anything
=> Change shadow steel recipe to be similar to the HV steel recipe

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8273
In early game especially, players might do the mistake of making an output hatch even though they wanted an input hatch for their first ebf, but currently there is no way to convert the busses or hatches to the other counterpart.
This adds screwdriver recipes to freely convert output <-> input
=> Adds conversion recipes to busses and hatches

src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java
Adds the missing indium boost from https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/967
Adds it to lcr instead of electrolyzer since electrolyzer would need circuit and would make the indium comb recipe multiblock only, but if that's preferred, I could change it.
Regular roquesite processing:
=> Add Roquesite indium boost

src/main/java/com/dreammaster/gthandler/nameRemover/NameRemover.java
The name remover will now remove various NBT tags that it was missing before such as the tank settings, the strong redstone signal.
Additionally you can now wipe the cover data by using a circuit 24, however it won't recover the cover (pun intended)
=> Improve the Name Remover machine

src/main/java/com/dreammaster/main/DebugHandler.java
If a mod cancels the `RenderGameOverlayEvent.Pre` for `type == DEBUG`, the lists `event.left` and `event.right` will be empty, therefore we need to check the sizes before adding to a specific index.
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:756)
at java.util.ArrayList.add(ArrayList.java:481)
at com.dreammaster.main.DebugHandler.onDrawDebug(DebugHandler.java:16)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_1336_DebugHandler_onDrawDebug_Text.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:699)
at …
```
=> Fix array out of bounds crash in DebugHandler

src/main/java/com/dreammaster/mixin/mixins/early/MixinMinecraft_ConfirmExit.java, src/main/resources/assets/dreamcraft/lang/en_US.lang
When FML encounters an error, the only way to quit the game is through the close button. This will show a "are you sure" dialog. Unfortunately, the dialog will show no message as locales have not been loaded yet at this stage. This adds a fallback message in English (same locale as the FML error).
Fixes the following:
=> Add fallback string for close window dialog

dependencies.gradle, src/main/java/com/dreammaster/scripts/ScriptAE2FC.java, src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17821
requires https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/615 and https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/615
Add recipes for preconfigured storage and fluid storage buses, from priority 1 to priority 24.
(tooltips added with CustomTooltips)
=> added preconfigured storage buses

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
fix proper recipe conflicts for firebox assembler recipes and bars.
fixes part of https://discord.com/channels/181078474394566657/522098956491030558/1315089195945033771
found with the nei custom diagram and checked with it afterwards.
=> fix a few recipe conflicts

src/main/java/com/dreammaster/scripts/ScriptAvaritia.java
Fixes a long standing bug where avaritia tools recipes dont show directly in NEI.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13386 and a bunch of duplicates.
that particular NBT being set to 0 or not existing is fully functionally equivalent.
=> Fix avaritia tool recipes in NEI

src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java, src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java, src/main/java/com/dreammaster/scripts/ScriptExtraTrees.java, src/main/java/com/dreammaster/scripts/ScriptThaumicExploration.java, src/main/java/com/dreammaster/scripts/ScriptThaumicHorizons.java
Related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17406
The last recipe is a meme recipe using various brews, teas, and Jäggermesiter
and a QOL recipe for getting the honney jar, since the only way is to place honney in world and click it
=> Added recipes in oreder to get currently unobtainable foods

src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
as described in the issue, 1080k Sp Coolant needs Fluxed Elextrum, which needs Trinium Coils which needs ZPM Assembler in LuV
changed the 1 1080k Sp to 2 540k Sp Coolant Cells
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18201
=> stop Luv solenoid being gated ZPM

src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16837
=> Add recipes for preconfigured p2ps

src/main/java/com/dreammaster/gthandler/recipes/FluidExtractorRecipes.java, src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
This PR removes the clear glass -> regular glass ebf recipes, since they were allowing for a godforge leveling cheese due to there also existing glass -> clear glass ebf recipes, forming a closed ebf loop.
Instead, there now are fluid extractor recipes for both clear glass panes and blocks with equal stats to those of regular glass.
=> Nerf glass loop 

src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Since recipes can only either be nbt sensitive or oredicted and not both, the artificial universe cell recipe ran into issues. This PR fixes that by swapping the oredicted circuits with magmatter nanites to remove the oredict requirement.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18466
=> Fix artificial universe cell recipes

src/main/java/com/dreammaster/gthandler/GT_Loader_OreDictionary.java
Remove the oredict which allows railcraft crowbars in place of gt ones in crafts (the only meaningful one being maintenance hatch). This served only to confuse people, as this only works with full durability crowbars and consumes them entirely (leading players to often ask why the craft is not working). There is no reason to allow this broken interaction.
=> Don't allow railcraft crowbars in crafting

src/main/java/com/dreammaster/scripts/ScriptNuclearControl.java
Replacing vanilla dyes with dyes from GregTech
A long time ago when setting up the autocraft of things from Nuclear Control noticed that the color module has a recipe with vanilla dyes. I found its recipe in the code and wanted to change it to use a similar color from other mods, but did not find how to do it, so I specified the use of dyes from GregTech. Is it possible to specify the use of dyes from any mod?
=> Color upgrade recipe change

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java, src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
- UEV+ casings did not have reversible bit set.
- UEV and UIV hulls had reversible set on their crafting table recipes (wrong) but since the casings had no data, they did not cause a dupe. Had the casings been set, you could dupe materials this way.
- Adds recycling data for UEV+ hulls the proper way
=> Fix UEV+ casing and hull recycling recipes

src/main/resources/assets/dreamcraft/lang/en_US.lang
This adds some missing localizations for unlocalized names returned by the ItemStack-insensitive version of `Item.getUnlocalizedName()`.
Relevant for the Item/Block stats introduced in https://github.com/GTNewHorizons/Hodgepodge/pull/398.
=> Add Localizations

src/main/java/com/dreammaster/amazingtrophies/AchievementHandler.java, src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18594.
Bug was introduced in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1128.
(The change `HashMap` -> `Map` has nothing to do with it)
=> Fix Ultra High Strength Concrete Floor Receipe

src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18682
The issue was caused by ae cells having an empty nbt tag when cheated in from nei, which the recipe was based on. 
Crafted ones do not have this tag which broke the recipe.
=> Fix artificial universe cell

src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
in nightly the log is full of gs recipe errors and the recipes dont show up in game either. This PR fixes them by simply switching to the gt api, as the error were about the gt tools in the recipes. 2 deco block crafting recipes are removed because those blocks are in the relevant chisel group.
I cant decide on the slogan for this PR:
Brings back the plasma hoe for all you vampires out there!
OR
I am a plasma hoe and it's not just a phase!
=> GS script recipes fixes

src/main/java/com/dreammaster/scripts/ScriptExtraUtilities.java, src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
nhcoremod part of https://github.com/GTNewHorizons/GT5-Unofficial/pull/3785
This part removes the recipes. It also changes the recipe for the enderquarry from the ic2 advminer to the T2 GT multiblock drill, which are similarly tiered, though the main cost and tiering of the recipe is elsewhere anyway so this does not change balance.
=> remove ic2 valuable ore compat, ic2 miner, and ic2 scanners

src/main/java/com/dreammaster/scripts/ScriptCoreMod.java, src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java, src/main/java/com/dreammaster/tinkersConstruct/MeltingRecipeAdder.java, src/main/java/com/dreammaster/tinkersConstruct/TConstructHelper.java
I'm going to be working in those files and the huge repetition annoyed me. Trying to lessen it somewhat.
Incidental changes: 
- redGranite cassiterite melted into half the amount as other versions of this ore for some reason, made it the same.
- For some reason rubber melted into glue at different temperatures. That didn't seem meaningful and worth keeping the extra calls so I unified it.
There should be no other functional changes. This should make my life easier when changing aluminium brass to brass as a casting material.
=> Streamline smeltery melting recipes

src/main/java/com/dreammaster/recipes/RecipeRemover.java, src/main/java/com/dreammaster/scripts/ScriptEFR.java, src/main/java/com/dreammaster/scripts/ScriptExtraUtilities.java
- replaces recipe for slightly larger chest from XU with the EFR barrel. functionally identical but just all around nicer.
- add recipe for EFR lantern similar to existing bibliocraft lantern recipe.
- adjust rabbit hide to leather recipe to work exactly like imp leather.
- add recipe for EFR blast furnace with plates instead of ingots.
=> More EFR recipe work

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Retiers Crafting Input Buffer, Crafting Input Proxy, and Advanced Stocking Input Hatch as discussed in https://discord.com/channels/181078474394566657/1326201379265449995.
Moves all parts to Space Assembler as well, since late game (UHV+) AE2 parts always go in space assembler now, these recipes were just old and now is a good time to move them.
Advanced Stocking Input Hatch: UEV -> UHV
Crafting Input Buffer: UIV -> UEV
Crafting Input Proxy: UV -> UIV
GT5u PR changing the casing textures on these parts to the new tiers: https://github.com/GTNewHorizons/GT5-Unofficial/pull/3766
|                     **Part**                     | **Old** | **New** |
|:------------------------------------------------:|:-------:|:-------:|
| **Advanced Stocking Input Hatch** _(UEV -> UHV)_ | …
=> Retier CRIB, proxy, adv stocking hatch

src/main/java/com/dreammaster/recipes/RecipeRemover.java, src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
Original code was removing all map recipes but only adding back the base one. This resulted in only the base zoom map being available and prevented things such as the navigation module for Open Computers from being able to be aware of a larger area.
Please let me know if more information is required.
=> Remove map recipe from crafting and recipe removal logic

src/main/java/com/dreammaster/scripts/ScriptGregtech.java
Makes the dust > dye conversions shaped to the first slot of the second row, allowing them to be done in the 2x2 crafting table and the full table.
Relies on GT5 pr (https://github.com/GTNewHorizons/GT5-Unofficial/pull/3838) to fix the recipe conflict in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16602.
=> Make the dust > dye recipes shaped

src/main/java/com/dreammaster/scripts/ScriptDraconicEvolution.java
Add dislocator recipe
Depends on this one
https://github.com/GTNewHorizons/Draconic-Evolution/pull/60
Changed obsidian slabs into plates, since I read somewhere that is planed to remove railcraft ( obsidian slabs are from railcraft)
=> Magnet Dislocator recipe

src/main/java/com/dreammaster/gthandler/recipes/FluidExtractorRecipes.java, src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java, src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
Added recipes from the drying rack into Dehydrator ( there where some, but others where missing), and also recipes that are usefull for magic stuff from items that where only obtainable from the smeltery into fluid solidifier
Solving old issue  https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12892#issuecomment-1467068167
=> Bunch of QoL recipes from an old issue

src/main/java/com/dreammaster/recipes/RecipeRemover.java, src/main/java/com/dreammaster/scripts/ScriptGregtechPlusPlus.java
Moves the gt++ fish trap recipe here since it depended on a coremod item
=> Move fish trap recipe from gt++ to coremod

src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
Reduces obsidian block processing (creating and using) to be 2 ingots worth of material universally, rather than mixed between 2 and 9.
Other PRs:
- GT: https://github.com/GTNewHorizons/GT5-Unofficial/pull/3969
- Modpack: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/19110
=> Reduce Obsidian Processing from 9 per block to 2 per block

src/main/java/com/dreammaster/scripts/ScriptRailcraft.java
(cherry picked from commit 2169c37c883ecacd2674222c71234cd599835f84)
After some discussion with Gleese
Quest changes
- https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/19116
Make Firestone be LV available to used as RC Boiler fuel in the "Steam Multiblock Age"
**old**
**new**
**old**
**new**
also use other varaint of firestone gem
=> RC Firestone for LV Age

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
Recipe was removed with tool removals. It is used to craft Electric Hoe of Growth
=> Add back electric hoe recipe

src/main/java/com/dreammaster/scripts/ScriptBiblioCraft.java
Fixed the ScriptBiblioCraft.java Pedestals recipe bug where only 7 out of 15 recipes were available
Moved the addShapedRecipe to line 767 under the TypeWriterB
=> pedestal recipe fix

dependencies.gradle, src/main/java/com/dreammaster/recipes/RecipeRemover.java, src/main/java/com/dreammaster/scripts/ScriptIronTankMinecarts.java, src/main/java/com/dreammaster/scripts/ScriptLoader.java, src/main/java/com/dreammaster/scripts/ScriptRailcraft.java
Add the Iron Tank Minecarts mod scripts.
The RC tank cart is now built with a BC Factory Tank
this patch needs a GT5 release with [this PR](https://github.com/GTNewHorizons/GT5-Unofficial/pull/4182)
=> Add Iron Tank Minecarts and unify Tank Cart recipes

dependencies.gradle, src/main/java/com/dreammaster/scripts/ScriptIronTankMinecarts.java
moving back to the old maven group in 1.0.5 and doing this early so scripts etc keep working smoothly for further updates
=> update irontanks and iron tank minecarts dependency

.github/workflows/test-forbidden-getmoditems.yml, .github/workflows/test-forbidden-ismodloaded.yml, src/main/java/com/dreammaster/main/MainRegistry.java, src/main/java/com/dreammaster/modcustomdrops/CustomDropsHandler.java, src/main/java/com/dreammaster/scripts/ScriptAmunRa.java, src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java, src/main/java/com/dreammaster/scripts/ScriptThaumicEnergistics.java, src/main/java/com/dreammaster/scripts/ScriptZZClientOnly.java
Similar to https://github.com/GTNewHorizons/GT5-Unofficial/pull/4208
Draft because it relies on a mod being added to the GT mods enum, which is added in #4208 (actions are run based on the scripts in master, so the tests pass in the PR. However once this merges, there will be a failure [here](https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/fb2f0037f9a8d2648e654a9f37f56096a47bbdcf/src/main/java/com/dreammaster/main/MainRegistry.java#L513))
=> Improve forbidden isModLoaded and getModItem scripts

src/main/java/com/dreammaster/gthandler/recipes/FluidSolidifierRecipes.java
Specifies for the Recipe to use Neutronium glass like it was before. This was causing an issue where the glass were used to craft itself.
=> Revert Oredict call on Electron-Permeable glass recipe

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
These buffers are crafted universally with wires, not cables. This keeps that consistency.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19366
=> Fix EV Battery Buffer 16-slot assembler recipe

src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
We really need to centralize the way crafting recipes are added in the pack
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19790
=> switch GalaxySpace addShapedRecipe to GTModHandler.addCraftingRecipe

src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
The case this is addressing
- dtpf with hypogen coils
- player wants to use comb recipes
- player wants to use the faster, but more expensive infinity recipe using awakened draconium coils. 
This requires program circuit 1, for cosmic neutronium, and program circuit 3 for infinity. In 2.7.x, circuit priorities were deterministic, and a knowledgeable player could order them in the bus such that 3 would take priority over 1, and both recipes would work as expected. 
However, on 2.8.x, (tested on build 1003). circuit priority is currently not deterministic. meaning the player can no longer use the recipes above in the same CRIB/bus.
If we were to change the program circuit used for the non-comb hypogen recipe to be one which is not shared with other recipes, the conflict goes away, and we no …
=> update dtpf infinity circuit to not share circuit with cosmicneut

src/main/java/com/dreammaster/scripts/ScriptBloodMagic.java, src/main/resources/assets/dreamcraft/lang/en_US.lang
This PR aims to buff the recipe for the incense altar by swapping out the apprentice blood orb with a blank slate.
It also adds a research page since it's now been moved to the arcane crafting table.
=> Buff the Recipe for the Incense Altar

src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java
removes recipe, Obzinite does not have Aluminum in it, like all other recipes.
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19964
=> remove Sodium Aluminate recipe with Obzinite

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
These recipes were added to upgrade lootbags is a way better than repeatedly clicking on the quest submission on questbook, but the recipes are all way too slow and it is considerably faster to just keep trading them via questbook instead.
This PR reduces the recipe duration so these recipes aren't useless and people don't continue to just manually press the quest submission button repeatedly.
=> Reduce Crafting time of lootbag conversion

src/main/java/com/dreammaster/scripts/ScriptEFR.java
Making it a 2:1 ratio makes it consistent with obsidian, and easier to make 1 calcite block for ore finder wand.
Calcite geodes currently give a ton of calcite, with a geode being able to have from 6-16 stacks of calcite blocks, which can currently make up to 144 stacks of calcite dust, which can make 5.5 million oxygen rather cheap and easily at 2 eu per oxygen at 1.6 seconds per 1000 oxygen for 1 mv electrolyzer. 
Getting around 12-32 stacks of calcite per geode is more reasonable, and it fulfills any early game BBF requirements with just 1 geode.
=> Nerf amount of calcite obtained from geodes

src/main/java/com/dreammaster/main/ClientProxy.java, src/main/java/com/dreammaster/main/CommonProxy.java, src/main/java/com/dreammaster/main/MainRegistry.java, src/main/java/com/dreammaster/scripts/ScriptZZClientOnly.java
This PR removes a dependency on GT methods that are being deleted,
It must be merged and build before the linked PR. https://github.com/GTNewHorizons/GT5-Unofficial/pull/4541
=> Remove access to GTMod isclient methods

src/main/java/com/dreammaster/scripts/ScriptMatterManipulator.java
The MK0 should be craftable in HV with some branching out to other mods (EIO, TC, etc). It shouldn't require an EV/IV material like tungstensteel. This reduces the field generator from MV to LV to fix this oversight.
=> Remove tunstensteel from MM MK0

src/main/java/com/dreammaster/gthandler/recipes/ForgeHammerRecipes.java
- Fixes forge hammer recipes for double compressed coal and charcoal, now outputting 9 of their compressed block variety rather than the gem itself. 
I will also follow this up by adding decompression recipes for cactus coal, cactus coke, sugar coal, and sugar coke, but in GT5u where their compression recipes are also located
This will fix and close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20532.
=> Fixes Decompression Recipes for Coal & Charcoal

dependencies.gradle, src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
for compatibility with changes made into GT https://github.com/GTNewHorizons/GT5-Unofficial/pull/4643
I also deleted the BITSD parameter from calls to GTModHandler.addMachineCraftingRecipe as it is now the default
=> Update calls to GTModHandler#addMachineCraftingRecipe

src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
- Changes previous sign recipes with vanilla wood planks to output appropriate new EFR sign rather than regular oak sign in both crafting and with the assembler
- Adds Cherry sign recipes in crafting and the assembler using the new cherry plank
- Adds in additional oak pressure plate recipe using pig iron spring for consistency with crafting recipes.
(All recipes done in reference to previously established recipes, nothing new)
This is a follow up to https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1300 and this chain will continue in small PR batches (for ease of review) until all recipes are integrated.
=> EFR - Change / Add Sign Crafting & Assembler Recipes

src/main/java/com/dreammaster/scripts/ScriptEFR.java
As title dictates, replaces sticks in armor stand recipe with impregnated sticks as suggested by Ender. 
This will fix and close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19930. (For the second time)
=> Fixes Recipe Conflict Between Armor Stand and Chisel

src/main/java/com/dreammaster/scripts/ScriptEFR.java
- Adds new recipes for oak, spruce, birch, jungle, acacia, dark oak, cherry, and bamboo boats & their boat w/ chest varieties.
- This still allows for the oak boat universal wood recipe, just adds specific recipes for the specific wood typed EFR items.
=> Adds recipes for EFR boats & boats with chests

src/main/java/com/dreammaster/scripts/ScriptEFR.java
adjustment to https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1316 for copper oxidation recipes
Divided by 20 the quantity of gas required to process blocks, as they are supposed to be decorative
=> divide by 20 the cost of the fluid for copper oxidation recipes

src/main/java/com/dreammaster/main/MainRegistry.java, src/main/java/com/dreammaster/travellersgear/TGConverter.java
Chest contains the stand's items and a Bibliocraft armor stand (they were interchangeable before TG was removed).
Only happens when TG is not loaded.
Example (TG items aren't transferred, obviously):
=> Convert Travellers Gear armor stands to a chest

src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java
In [NeiCustomDiagram we remove](https://github.com/GTNewHorizons/nei-custom-diagram/blob/master/src/main/java/com/github/dcysteine/neicustomdiagram/generators/gregtech5/oreprocessing/RecipeHandler.java#L218) recipes from the output if there is more than one.
With this [PR](https://github.com/GTNewHorizons/GT5-Unofficial/pull/4540) in GT5U Desh became an ore-dict which causes it now to have two macerator recipes.
Remove the now clashing of the Macerator Recipe for Desh Ore since its now handled via the oredict
=> Fix: Remove direct Macerator Recipe which causes issue with nei-custom-diagrams

src/main/java/com/dreammaster/gthandler/recipes/VacuumFreezerRecipes.java
Tantalum was a major outlier in freezing time (longer to cool than HSSG or TungstenSteel ingots), this PR brings more in line. MV chembatch recipe untouched
=> bring tantalum freeze time to a reasonable level

src/main/java/com/dreammaster/gthandler/recipes/ForgeHammerRecipes.java
As crushed obsidian only has a blast resistance of 27 and isn't used in any recipes, I tiered it to LV.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19369
=> Add recipe for crushed obsidian

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java, src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
- Adds in recipe for super stock replenisher, UV gated since it performs UV gated actions (stocks fluids)
- Changes void cell recipe to more closely mimic the fluid void cell recipe (replaced ender eye with ae2 singularity)
(There will also be a quest for SSR it's coming in a sweep probably tomorrow)
=> Adds Recipe for Super Stock Replenisher & Makes Void Cell Recipe Consistent

src/main/java/com/dreammaster/gthandler/recipes/ChemicalBathRecipes.java
- Simple change, adds extra recipes using more expensive HV rubbers for guaranteed EIO conduit binder out of chemical bath.
The regular recipe takes normal rubber and makes it a percent chance output, which is messy for AE2 recipes. The more expensive later tier rubber giving access to slightly more of this relatively insignificant resource should not create any balance problem and would only serve as QoL. 
(There's no issue to reference on this, it's just a feature I've seen requested by a lot of players)
=> Adds Alternate Rubber Recipes for EIO Conduit Binder

src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
istg I hope this is it. This removes the nickel and platinum ores that have smelting added for some reason, removes gear melting for a few alloys and nickel, and finally fucking removes the damned silver cluster recipe. Also adds electrum ingot melting for the purpose of making brownstone. 
Also! Those cluster recipes are added by witching gadgets, which adds iron, gold, copper, tin, silver, but not lead for some reason. idk if we want to remove the recipes from there directly, but yeah.
tested in full pack since apparently neither the scripts nor thaumcraft are in the dev env, and its 4am and I cant be assed to figure it out rn
=> Remove the rest of the gear smelting and several metals

src/main/java/com/dreammaster/gthandler/recipes/MaceratorRecipes.java
Just a quick QoL to recycle Hempcrete back into Hempcrete Powder in case you made too much of the former but wanted the latter.
Recipe duration and EU/t are copied over from Stone to Stone Dust recipe
Example (other colors have corresponding recipes):
=> Add macerator recycling recipe from Hempcrete back to Hempcrete Powder

src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- Refactors a bunch of repeating code so that it's relatively easy to enter in new lootbag recipes if we introduce more, it should be very easy to add new pairs of bags and change quantity or voltage for balance reasons (I might do the same for the coins)
- Adds new recipes for AE2 bags, witchery bags, and HEE bags that weren't there before
This can be merged at any time safely, but is meant as a sister PR to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/21067
=> Adds Missing Lootbag Assembler Recipes (& Light Refactor)

src/main/java/com/dreammaster/scripts/ScriptEFR.java
Adds EFR concrete variants to the hempcrete and hempcrete powder chisel groups
This PR does not change anything by itself, it should be approved along with https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/21105, which enables concrete in the EFR configs
Block color comparison, rows 1 and 3 from the the are Hempcrete, rows 2 and 4 are concrete:
Hempcrete chisel group:
Hempcrete Powder chisel group:
=> Add Chisel recipe for EFR Concrete and Concrete Powder

src/main/java/com/dreammaster/scripts/ScriptMatterManipulator.java
Was originally going to tack this onto #1360.
This PR just makes the matter manipulator script more consistent by using GTOreDictUnificator for all the circuit lookups.
=> Make circuit oredict lookups consistent by using GTOreDictUnificator

src/main/java/com/dreammaster/scripts/ScriptThaumcraft.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21114
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1324 changed the recipes for the three foci. They were accidentally overwritten which also caused the linked issue. This PR restores them to the intended Botania quartz variants.
Recipes now:
=> Restore overwritten recipes for Warding, Portable Hole, Nine Hells foci

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java, src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
As this comment mentioned the change in PR https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1278#issuecomment-2910951502, T2 and T3 got their controller recipes changed to use their respective Air Filter casings
Ignore this if the change is too much (like, i just make a PR so all tiers follow the same logic
The difference in tungsten price for a controller:
1. previous one (just default turbine casing)
2. done in assembler (cheaper cost)
3. done in crafting table (the most expensive)
The same costs follow other tiers, just motor tier and metal changes (lv and steel, hv and titanium, iv and tungsten)
=> Change T2 and T3 air filter recipes.

src/main/java/com/dreammaster/gthandler/recipes/ChemicalBathRecipes.java, src/main/java/com/dreammaster/recipes/RecipeRemover.java, src/main/java/com/dreammaster/scripts/ScriptProjectRed.java
- Moved cable dye recipes to ScriptProjectRed instead of chemical bath recipes; makes more sense this way
- Got completely rid of the "ProjectRed Crafting" tab that's custom made by the mod and clutters NEI for no reason, replaced with our GT version
- Changed the recipes for all framed wire variants, they all used forge microblocks (ew, I know) before. Now they still have the same cost, but in sticks for crafting, and have an added packager recipe that is consistent with the already greggified wire recipes- not sure why these ones were looked over before.
- Added unpackager recipes, and changed a couple unpackager recipes that fabricated rubber sheets out of thin air
- Moved around code, and refactored it into much neater loop code for readability (which is why there are so many line …
=> ProjectRed Framed Wire GT Recipes & PR Wire Refactor

src/main/java/com/dreammaster/scripts/ScriptEMT.java
- As title states, allows recipe to be viewed in NEI even at 100%. 
Update: This NBT was put in to keep shears mode disabled by default upon craft, but it didn't work anyway. So I'm just taking it out. This is a toggleable feature nonetheless
This will close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14628
=> Fixes Diamond Chainsaw in NEI

src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
Noticed these blocks were uncraftable, which was a shame since they look quite good. This PR makes them obtainable via chiseling their GT equivalents.
=> Add chisel recipes for BoP Tanzanite and Topaz blocks

src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
- As title states, recipes were added to GT5u in a much more complete way in https://github.com/GTNewHorizons/GT5-Unofficial/pull/4634 they don't belong here any longer.
=> Removes Duplicate Recipes for Compressed Glowstone

src/main/java/com/dreammaster/modctt/CustomToolTips.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21405
As shown in the issue, extra tooltip lines with charging info gets thanos snapped as the items get charged or used because Meta ID changes.
This change allows to specify Meta ID range for such items by specifying it in the XML file (MetaStart and MetaEnd). If they are not specified, they are set as null and ignored in the FindItemToolTip and uses only old values/comparisons.
The affected items (from [linked](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/21431) config change PR): Oreberries, Backpacks, ETM, Thaumic Boots, Gravisuit, IC2
After:
https://github.com/user-attachments/assets/90f2104e-1d48-4c6a-8fcb-257ab315839f
Other vids can be found here with before, after, and side comparison: …
=> Allow for usage of MetaID range (MetaStart and MetaEnd) to specify the custom tooltip

src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java, src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
basically just moves the barnarda C base wood recipe. That is enough to fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21564
There must have been some problem with load order or the recipe adder or something, I don't actually know the cause of the bug.
now it works:
=> Fix Barnarda C plank recipes
