GTNewHorizons/NewHorizonsCoreMod

- .gitignore
- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/9d0c1dcb406cfcad9dc93e1d9922fb5fa6695854
> added comments on OC, added Thaumic Bases Pulveriser recipe

- src/main/java/com/dreammaster/oredict/OreDictHandler.java
- src/main/java/com/dreammaster/oredict/OreDictTypes.java
Stops redstone from centrifuging into planet mercury dust :)
> Don't oredict planet mercury dust to mercury dust.  

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
fix for fused glass in alloy smelter (circuit for fused glass, mold for vanilla glass),
chembath recipe for dark fused quartz & dark fused glass (so it will accept liquid fluid aswell),
> one fix one new recipe

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
https://github.com/GTNewHorizons/NewHorizons/issues/2842
> fixes 2842, adds missing ZnO -> Zn EBF Recipe, Stargate Rebalance

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
+ since its an assembler recipe its a bit cheaper
https://github.com/GTNewHorizons/NewHorizons/issues/2852
> Woven Cotton needs assembler recipe #2852

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
new recipe for https://github.com/GTNewHorizons/NewHorizons/issues/2999
@noobyaran9
> new recipe for #2999

- src/main/java/com/dreammaster/main/MainRegistry.java
Because of java/gregtech/forge mod loading order, have to implement the config option to disable MACHINE_METAL tinting here in the core mod.
> Fix to support disabling MACHINE_METAL tinting on machines.

- src/main/java/com/dreammaster/gthandler/GT_Loader_Batteries.java
fix https://github.com/GTNewHorizons/NewHorizons/issues/3656
> fix UV battery

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
I use Superconductor UV for construction SupCond Coil
> Add new recipe for SupCond Coil

- src/main/java/com/dreammaster/oredict/OreDictHandler.java
-added blockOlivine as blockPeridot in OreDict https://github.com/GTNewHorizons/NewHorizons/issues/3952
-fixed Venus Blocks OreDict Issure https://github.com/GTNewHorizons/NewHorizons/issues/3949
> OreDict changes

- README.md
Update to README to add brief description of mod so we can upload to twitch. If they require more detail ping me and I'll add more.
> Update readme twitch desc

- build.gradle
- src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java
- src/main/java/com/dreammaster/fluids/ExtendedFluidCollection.java
- src/main/java/com/dreammaster/fluids/FluidList.java
- src/main/java/com/dreammaster/gthandler/GT_CoreModSupport.java
- src/main/java/com/dreammaster/main/MainRegistry.java
> Added Radox + Bartworks

- build.bat
- build.gradle
> changed forge's maven to overminddl1's maven

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
https://github.com/GTNewHorizons/NewHorizons/issues/3540
https://github.com/GTNewHorizons/NewHorizons/issues/4103
https://github.com/GTNewHorizons/NewHorizons/issues/4102
https://github.com/GTNewHorizons/NewHorizons/issues/4096
> added recipes:

- build.properties
- src/main/java/com/dreammaster/main/MainRegistry.java
- src/main/java/com/dreammaster/modfixes/GTpp/GregTechPlusPlusAbandonedAspectsFix.java
+will hopefully doesnt cause corruption when loaded up
> added Abandoned GregTechPlusPlus Aspects

- src/main/java/com/dreammaster/gthandler/CustomItemList.java
- src/main/java/com/dreammaster/gthandler/GT_CustomLoader.java
- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
+added UIV & UMV Circuit Assembler (currently disabled)
+added UHV, UEV, UIV to the customLoader
+reworked comments on Loader Machines
> added UHV & UEV Circuit Assembler

- build.gradle
- src/main/java/com/dreammaster/gthandler/CustomItemList.java
- src/main/java/com/dreammaster/gthandler/GT_CustomLoader.java
- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
depends on https://github.com/GTNewHorizons/GT5-Unofficial/pull/199
Will crash if bartworks <0.5.1 is installed (not needed for testing)
> added UHV/UEV machines

- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
> fix UIV+ Circuit Assemblers

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
- src/main/java/com/dreammaster/main/MainRegistry.java
+added localisation
+fixed some alloy/plate issues
> fixes 4 item minium requirement

- build.properties
- src/main/java/com/dreammaster/bartworksHandler/BW_New_Ores_Loader.java
- src/main/java/com/dreammaster/bartworksHandler/BW_Recipe_Loader.java
- src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java
- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
+added basic BW Small Ores (disabled on any Dim w/o config changes)
> fixed implosion recipe for T4 plates

- src/main/java/com/dreammaster/bartworksHandler/BW_New_Ores_Loader.java
> corrected values

- src/main/java/com/dreammaster/bartworksHandler/BW_New_Ores_Loader.java
> +subgrouped small veins

- build.gradle
- build.properties
- src/main/java/com/dreammaster/bartworksHandler/BW_New_Ores_Loader.java
- src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java
> put BW small ores in the runnable

- build.gradle
- build.properties
- src/main/java/com/dreammaster/bartworksHandler/BW_New_Ores_Loader.java
+contains Mercury/Sulfur, Mercury/Chlorine/Oxygen, Palladium/Mercury, Palladium/Mercury/Tellurium ores
> added mercury vein

- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
Change circuits in UV and UHV TurboChargers
> Fix recipes of TurboChargers

- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
https://github.com/GTNewHorizons/NewHorizons/issues/5366
> Fluxed electrum no mixer recipe, only shapeless #5366

- src/main/java/com/dreammaster/oredict/OreDictHandler.java
See: https://github.com/GTNewHorizons/NewHorizons/pull/5529
> feat(oredict): add fenceWoodRegistration

- build.gradle
- build.properties
- src/main/java/com/dreammaster/gthandler/accelerator/GT_MetaTileEntity_WorldAccelerator.java
+ added deObfs jar
+ added soruces jar
> Added an API WA Endpoint

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Confirm the recipes are working and crafted fluid is accepted by Binnie's Machines. Changed the voltage to 60eu/t per request
> Added remaining Bacteria from Binnie's to GT Brewing machine

- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6630
> fix LUV-UEV Scanner recipes

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> Chlorine cleaning of pistons #3137

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
GT converting recipe no working
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6790
> Fix & Remove Mining Pipe - Converting

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6495
> 100 -> 144 for pico wafer

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
moves the implosion compressor recipes to code
> move imlosion recipe to code

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
In the compressor
Should fix!: [#4602](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4602) (Not tested ingame)
> Added ardite ingot to block recipe

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
(Not Tested) - did this during lunch at work
> Try to move TC metals to Core Mod

- build.properties
- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
reactivate GT Tools crafting (only assembler LV/MV)
add recipe for Steel how need for the Electric hoe (shaped)
re-add recipes for shape forms
> reactivate GT Tools

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
[#7373](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7373)
> Fix Sunnarium

- src/main/java/com/dreammaster/gthandler/GT_Loader_CasingNH.java
- src/main/java/com/dreammaster/main/MainRegistry.java
Fixes GTNewHorizons/GT-New-Horizons-Modpack#7515
> Fix classloading order when not all mods are loaded

- src/main/java/com/dreammaster/gthandler/GT_Loader_Materials.java
Smeltery recipe is 5:2:2 parts make 2 parts, Dust recipe prior to commit d760009 is 5:2:2 makes 9 parts.
> Nerf alumite dust recipe. 

- src/main/java/com/dreammaster/gthandler/GT_Loader_Materials.java
Reverts GTNewHorizons/NewHorizonsCoreMod#161
Balance change was not properly discussed before being implemented
> Revert "Nerf alumite dust recipe. "

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
for helmet, chestplate, leggings and boots molds
> add fluid solidifier & forming press recipes

- src/main/java/com/dreammaster/coremod/DepLoader.java
- src/main/java/com/dreammaster/coremod/DreamCoreMod.java
- src/main/java/com/dreammaster/coremod/DreamTransformer.java
1. GTNewHorizons/GT-New-Horizons-Modpack#7714
2. Fix ineffective config option to disable warding focus patch. It was doing nothing before. Now setting it to false correctly remove the patch.
> Coremod cleanup

- src/main/java/com/dreammaster/gthandler/multiAirFilter/GT_MetaTileEntity_AirFilter.java
Also made clear how fast the machine clean up pollution
Signed-off-by: Glease <4586901+Glease@users.noreply.github.com>
> Fix air filter accepting non turbine tools

- src/main/java/com/dreammaster/gthandler/multiAirFilter/GT_MetaTileEntity_AirFilter.java
This thing thought it would work once a minute, but in fact it works once every 10 seconds.
> Fix air filter info data

- src/main/java/com/dreammaster/config/CoreModConfig.java
- src/main/java/com/dreammaster/main/MainRegistry.java
- src/main/java/com/dreammaster/modfixes/gravisuite/HoverModeFix.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7855
> Make gravisuit armor hover mode not fall when idle

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5502
> Make cooling Infinity ingots more reasonable

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7618, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7630.
@rv-jgentile this is how you do it in code.
You can also go to https://gtnh.miraheze.org/wiki/Development for more info.
> Re-add oreberry maceration recipes

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7912
> Remove extra version of astral silver recipe

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7602
> Add 9x ghast tear saltwater recipe

- src/main/java/com/dreammaster/gthandler/multiAirFilter/GT_MetaTileEntity_AirFilter.java
GTNewHorizons/GT-New-Horizons-Modpack#7997
Key points:
1. Remove pollution once per tick instead of once at the start of each duty cycle. This is to prevent the exploit of turning air filter on and off in quick succession with machine controller cover to remove huge amount of pollution rapidly with minimal  consumption.
2. Fixed info data to not display negative EU usage.
> Fix air filter related issues

- build.gradle
- build.properties
- src/main/java/com/dreammaster/baubles/OvenGlove.java
- src/main/java/com/dreammaster/baubles/WitherProtectionRing.java
- src/main/java/com/dreammaster/config/CoreModConfig.java
- src/main/java/com/dreammaster/main/MainRegistry.java
- src/main/java/com/dreammaster/main/NHItems.java
- src/main/java/com/dreammaster/modhazardousitems/HazardDamageSources.java
- src/main/java/com/dreammaster/modhazardousitems/HazardEffect.java
- src/main/java/com/dreammaster/modhazardousitems/HazardousItems.java
- src/main/java/com/dreammaster/modhazardousitems/HazardousItemsHandler.java
- src/main/java/com/dreammaster/modhazardousitems/cause/HazardCause.java
- src/main/java/com/dreammaster/modhazardousitems/cause/InventoryItemHazardCause.java
Gloves now don't grant your fire resistance.
Gloves protect you hot items (both in HazardousList and from GT (Molten cells, for example))
Slightly increased the period between damage from inventory items to make it closer to the period of molten items damaging. (the last is still twice slower)
Gloves protect you only if you hold the hot item.
Gloves doesn't protect you from items, which are not held, even if you held the hot item.
Information about the gloves been wrongly worn by other player shouldn't be shown to all nearby now.
Should be merged after:
https://github.com/GTNewHorizons/Yamcl/pull/2
https://github.com/GTNewHorizons/GT5-Unofficial/pull/635
> Rewritten logic of Gloves

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8439
If no one oppose the change let's merge this.
> buff ilmenite blast recipe to make it less absurd

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8560
> Fix CC recipes

- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
* https://github.com/GTNewHorizons/GT5-Unofficial/pull/707
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8743
> make internal Tank of the Cutter bigger

- build.properties
I want to update my mod to depend on the recent NAND circuit change. Need to bump the version so that I can depend on core mod > new version.
> Bump version

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
60 sec Chemical Bath at 120 eu/t
> Set Kanthal Coil to MV (Coolant recipe)

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9172
> Add bulk wood plate

- build.gradle
- repositories.gradle
> update build, https

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9405
> added 1 and 8 EU solar panels to the assembler

- src/main/java/com/dreammaster/scripts/ScriptBiblioCraft.java
- src/main/java/com/dreammaster/scripts/ScriptBiblioWoodsBoP.java
- src/main/java/com/dreammaster/scripts/ScriptBiblioWoodsForestry.java
- src/main/java/com/dreammaster/scripts/ScriptBiblioWoodsNatura.java
add back the missing recipes for theses items:
fixes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9323
> various fixes

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Partially addresses https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9417. (Don't close it yet)
> Fix conflict in Ztones Garden Soil

- src/main/java/com/dreammaster/gthandler/GT_Loader_Batteries.java
> Re add thaumcraft aspects and make them actually usuable this time.

- build.gradle
- src/main/java/com/dreammaster/bartworksHandler/BW_Recipe_Loader.java
- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Partially fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6107 (quest still need to be changed to remove the notice that bart something something)
> Fix not using ruridit bolt in T4 plate

- src/main/java/com/dreammaster/bartworksHandler/BioItemLoader.java
- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Change recipes using Circuit 0 in their recipes #9818
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9818
> Circuit0 fix

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9611
> possible fix for New recipe of extra cells 2 storage components oredict #9611

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
add natura barley to compress plantball recipes
(cherry picked from commit 2cbfff2735251ea4197a7379c0b5700181b443eb)
> add filing cabinet mv assembler recipe

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9867
> Fix dupe by disassembling Firebricks

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
https://discordapp.com/channels/181078474394566657/401118216228831252/954562425364054046
> Change configuration for Storage Components

- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
Merge alongside https://github.com/GTNewHorizons/GT5-Unofficial/pull/1076 please.
> Give fluid support to higher tier laser engravers.

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Merge with https://github.com/GTNewHorizons/GT5-Unofficial/pull/1085.
> Adjust mixer recipes for SC and add final UEV recipe.

- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
Same as https://github.com/GTNewHorizons/GT5-Unofficial/pull/532
> Change recipe for UV 16A Transformer

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10774
> Remove singleblock recipe from Aluminium Hydroxide

- src/main/java/com/dreammaster/config/CoreModConfig.java
- src/main/java/com/dreammaster/main/ClientProxy.java
- src/main/java/com/dreammaster/main/DebugHandler.java
Config option included, useful to immediately check the modpack version when reporting an issue.
> Display modpack version in debug GUI

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
https://chemistry.stackexchange.com/questions/25045/how-to-convert-sodium-aluminate-back-to-sodium-hydroxide
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10774
> Make Aluminium Hydroxide actually craftable at MV

- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
Chest buffer requested:
- https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10198
> fixing random high endgame machine recipe

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10764
numbers are from old MT script
> Fix recipe for Ztones Booster

- src/main/java/com/dreammaster/oredict/OreDictHandler.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10620
I have zero idea why `forEach` is not working tbh
> Fix Block of Olivine not being registered as blockPeridot

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Added dtpf recipes for sc base uiv and umv
Adjusted sc base uev to be based off of oganesson smelting instead of radon smelting
> Superconductor dtpf recipes

- src/main/java/com/dreammaster/scripts/ScriptAvaritiaAddons.java
as I've been asked here https://github.com/GTNewHorizons/Avaritia/pull/21
> add craft to infinity egg from witchery

- dependencies.gradle
- src/main/java/com/dreammaster/scripts/ScriptAlveary.java
- src/main/java/com/dreammaster/scripts/ScriptLoader.java
> Moved industrial Apiary to Coremod

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
Stops more exploits surrounding high tier casings.
> No reversing

- dependencies.gradle
- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
- src/main/java/com/dreammaster/scripts/ScriptLoader.java
Discretizer:
Pattern Encoder:
Pattern Decoder:
Dual Interface:
Ingredient Buffer:
Large Ingredient Buffer:
Fluid Import:
Fluid export:
Fluid P Terminal:
Processing terminal:
Cell recipes in CA are the same as the normal item ones, just with more pumps.
> Moves AE2FC recipes to coremod and made them more greggy

- src/main/java/com/dreammaster/scripts/ScriptEC2.java
Adds recipes for the two new cells: https://github.com/GTNewHorizons/ExtraCells2/commit/e7f896bb8734e20cb70f98c83601d01bf41e9a57
> Add recipes for ME Quantum Storage and ME Digital Singularity

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Less efficient but enables people to get an inf coil DTPF with less VM spam.
> Add new inf recipe for DTPF

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Added recipes for DTPF that use half the time and plasma consumption using infinity and cosmic neutronium combs + added configured circuits so all recipes for infinity work
> Added Infinity and Cosmic Nt Comb Catalyst Recipes to DTPF

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/11168
> add recipes from script to core mod

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
This Item has no use any longer.
> removed unused item recipe from Netherstarfragment

- dependencies.gradle
- src/main/java/com/dreammaster/scripts/ScriptLoader.java
- src/main/java/com/dreammaster/scripts/ScriptNuclearControl.java
> Add recipe for NC2 panel memory card

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
There is no reason to make player have entire extruder(or bus) for 1 recipe
> Fix Glass Fiber Wiremill Recipe

- src/main/java/com/dreammaster/loginhandler/LoginHandler.java
> minor text change

- dependencies.gradle
- src/main/java/com/dreammaster/bartworksHandler/BW_RadHatchMaterial.java
- src/main/java/com/dreammaster/bartworksHandler/BW_Recipe_Loader.java
- src/main/java/com/dreammaster/main/MainRegistry.java
https://github.com/GTNewHorizons/GTplusplus/pull/339
> rad hatch compact

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Apply proper plasma discount to bee catalyst recipes
> Dtpf bee part2

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9384
> convert ticon dusts to gt dusts in some recipes

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
add assembler recipes
* https://github.com/GTNewHorizons/GT5-Unofficial/pull/1397
> Clean room

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10056 - Reduce the chance of getting surprised like that
See also: https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/286
> Use the same number for programmed circuit and item meta except for 0 in Ztones recipes

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9818
> Remove circuit 0

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Roasted Zinc takes its place now https://discord.com/channels/181078474394566657/1030614224583540859
> Remove Zincite EBF recipe

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
- add recipe for me output hatch
- add superconductor coil recipe with uev+ superconductor
> recipe for me output hatch and more superconductor coils

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> Tps card craft

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> Spotless for 436

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> hypogen->infinity coil

- build.gradle
- src/main/java/com/dreammaster/scripts/ScriptAFSU.java
> AFB should use all iv circuits

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/GT_Recipe_Remover.java
change tantalum capacitor recipes
> Tantalum change

- src/main/java/com/dreammaster/modhazardousitems/HazardousItemsHandler.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11155
> Make hazmat-proof armors protect player from custom hazard effects

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11893.
> Fix Honey for Biomass

- dependencies.gradle
- src/main/java/com/dreammaster/bartworksHandler/BWGlassAdder.java
- src/main/java/com/dreammaster/main/MainRegistry.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11894
> add reinforced glass alfglass managlass as boroglass replacement in multi structure

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12057
tested in full game and works.
> Fix melodic capacitor recipe

- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
add fluid buffer recipe
add fluid terminal recipe
> add recipe

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
(cherry picked from commit 14f0dcb6f758d90dd5377cf57e3bb3ceb87b522d) 
* https://github.com/GTNewHorizons/GT5-Unofficial/pull/1588
> Add a cheaper recipe with Helium Gas for SiSG ingots in EBF

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
add pulverizer and arc furnace recipe
> Mining pipe recycling

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> add smd inductor recipe variant

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> add ducttape recipe

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12116
> Fix too many zeroes

- src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
Gated at ZPM with a single Mysterious Crystal per card.
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/218
> Add recipe for Hyper-Acceleration Card

- src/main/java/com/dreammaster/scripts/ScriptLoader.java
- src/main/java/com/dreammaster/scripts/ScriptTwilightForest.java
+ rearranged order of script loading to keep consistency
> Add Roof Tile (TF) recipe

- src/main/java/com/dreammaster/gthandler/CustomItemList.java
- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
(don't know why but dynamo and their both wireless version were already there)
> Add UXV Energy Hatch (without recipe)

- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
UHV-UMV Hi-Amp transformers recipes inufucation.
> Hi-Amp Transformers recipe unification

- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
> recipe for ae2fc's fluid storage bus

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
@TheEpicGamer274 i make this pr from your branch. Is thie ready or need more additions ?
> Quad Input Hatch recipes (#488)

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
> merge master 

- dependencies.gradle
- src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
Add-on to:
* https://github.com/GTNewHorizons/EnderIO/pull/89
This PR should not be merged until after that PR is merged.
> Replace creative staff of travelling with teleport staff

- build.gradle
- src/main/java/com/dreammaster/scripts/ScriptEC2.java
a shapeless recipe to turn ec item cell in ae2 one. the cell's storage contents can be kept so no need for using me-io to transfer. but the filter and upgrade will be lost
> add covert recipe between ec and ae large cell

- src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12435.
> Apiary with oredict

- src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12463
also readds all the circuit recipes lol.
> Fix around 100 critical recipes

- src/main/java/com/dreammaster/gthandler/recipes/FluidSolidifierRecipes.java
[#71](https://github.com/GTNewHorizons/TinkersConstruct/pull/71)
> Lock Reinforcement behind steel instead

- src/main/java/com/dreammaster/gthandler/recipes/BlastFurnaceRecipes.java
Added 9000L of Carbon Monoxide output to EBF recipe for Rutile + Wrought Iron
Closes GTNewHorizons/GT-New-Horizons-Modpack#12485
> Added carbon monoxide output to rutile EBF recipe

- src/main/java/com/dreammaster/scripts/ScriptAvaritiaAddons.java
Fix Infinity Chest (part of ec2 cleanup)
> Fix Infinity Chest

- src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12544
> Fix new Ae2 component recipes

- src/main/java/com/dreammaster/gthandler/recipes/CentrifugeRecipes.java
Fixes [this](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8985) by removing tiny dusts from iridium and dried bees.
> Remove tiny dusts

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12468
> Disable recycling concrete bucket

- src/main/java/com/dreammaster/coremod/BibliocraftTransformer.java
- src/main/java/com/dreammaster/coremod/DreamCoreMod.java
needs to be merged with https://github.com/GTNewHorizons/Hodgepodge/pull/183
> move the ASM to remove bibliocraft recipes from Hodgepodge to Dreamcraft

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
> Fix Hull inside quad UIV hatch

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
> Chang drill head shape recipe

- build.gradle
- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/GT_Recipe_Remover.java
- src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
ME conduits moved from script into code
add recipe for Ultra Dense ME cables
change recipe like the me cable recipes
update bs+sa
update dep files
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/13005
> Ender io recipes

- src/main/java/com/dreammaster/gthandler/GT_Recipe_Remover.java
- src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
Covered Cables are cheaper now than smart cables.
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/13009
> Ae2 cables change

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adds a recipe for the humongous input hatch, it is gated quite late to not invalidate hatch progression
> Add recipe for humongous input hatch

- src/main/java/com/dreammaster/scripts/ScriptIndustrialApiary.java
Since the Industrial Apiary is in HV now, I changed the upgrades needing HV materials too. This was supposed to be done with the downgrade of the industrial Apiary, but I forgot. 
The Osmium and Palladium Gears were changed to steel and stainless steel gears.
> Adjust according to tier

- dependencies.gradle
- src/main/java/com/dreammaster/scripts/ScriptIndustrialApiary.java
Same as light but with reinforced dark glass
For https://github.com/GTNewHorizons/GT5-Unofficial/pull/1821
> Add recipe to night upgrade

- src/main/java/com/dreammaster/gthandler/recipes/FluidSolidifierRecipes.java
recipe was added here https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/495 and later adjusted here https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/508.
But it never worked. Now it does.
> Fix Reinforcement recipe

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
fix small mistake in the new rocket assembler recipes.
> Fix rocket recipes

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- fix some incorrect ids from ec to ae2. fixes a bunch of broken recipes.
- recipes for 'me upgrades', now produce the new oc items instead of the old ec ones.
> Some more extracells cleanup

- build.gradle
- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/GT_CustomLoader.java
- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptAvaritia.java
- src/main/java/com/dreammaster/scripts/ScriptBloodMagic.java
- src/main/java/com/dreammaster/scripts/ScriptEMT.java
- src/main/java/com/dreammaster/scripts/ScriptExtraBees.java
- src/main/java/com/dreammaster/scripts/ScriptExtraUtilities.java
- src/main/java/com/dreammaster/scripts/ScriptForbiddenMagic.java
- src/main/java/com/dreammaster/scripts/ScriptForestry.java
- src/main/java/com/dreammaster/scripts/ScriptGadomancy.java
- src/main/java/com/dreammaster/scripts/ScriptMagicBees.java
- src/main/java/com/dreammaster/scripts/ScriptRunicTablet.java
- src/main/java/com/dreammaster/scripts/ScriptTCCoreMod.java
- src/main/java/com/dreammaster/scripts/ScriptThaumcraft.java
- src/main/java/com/dreammaster/scripts/ScriptThaumicBases.java
- src/main/java/com/dreammaster/scripts/ScriptThaumicEnergistics.java
- src/main/java/com/dreammaster/scripts/ScriptThaumicExploration.java
- src/main/java/com/dreammaster/scripts/ScriptThaumicTinkerer.java
- src/main/java/com/dreammaster/scripts/ScriptWarpTheory.java
- src/main/java/com/dreammaster/scripts/ScriptWitchery.java
- src/main/java/com/dreammaster/thaumcraft/TCHelper.java
Need this pr
* https://github.com/GTNewHorizons/GT5-Unofficial/pull/1893
> Fix materials

- src/main/java/com/dreammaster/gthandler/recipes/BlastFurnaceRecipes.java
makes ilmenite EBF recipe Chemically Rebalanced™
> Ilmenite Chemical Rebalance™

- src/main/java/com/dreammaster/gthandler/GT_Recipe_Remover.java
- src/main/java/com/dreammaster/scripts/ScriptForbiddenMagic.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13413
> Remove normal recipes

- src/main/java/com/dreammaster/gthandler/GT_CustomLoader.java
- src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
Directly change chrome to rhodium palladium if BW exists.
> Integrate BW material replacements

- src/main/java/com/dreammaster/oredict/OreDictHandler.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12497
> Add ingotHot oredict for Hot Nether Brick

- src/main/java/com/dreammaster/gthandler/recipes/ElectrolyzerRecipes.java
I didn't notice this recipe when I was doing other changes with alumina recipes because it was in centrifuge
also merge this https://github.com/GTNewHorizons/GT5-Unofficial/pull/1956
> Add brick electrolyzer recipe instead of centrifuge and adjust brick formula to a more reasonable one

- src/main/java/com/dreammaster/gthandler/GT_Recipe_Remover.java
Mimic https://github.com/GTNewHorizons/CraftTweaker/blob/translator/src/main/java/minetweaker/mc1710/recipes/MCRecipeManager.java#L307 correctly
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13479
> Fix recipe remover

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Assembler Recipes for Eye of harmony Required parts & components, anymore that need to be added contact me.
> Assembler recipes for some crafts

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Some small recipe fixes for the new recipes added to the optical circuit line
> Small recipe fixes

- src/main/java/com/dreammaster/gthandler/recipes/VacuumFreezerRecipes.java
These hot ingots dont exist. With ra2 they actually show up. So it's best to remove them.
> Remove 3 broken vac freezer recipes

- src/main/java/com/dreammaster/gthandler/recipes/VacuumFreezerRecipes.java
somehow I found another bad recipe in the vac freezer file. This is for a different reason though: there were 2 slightly different recipes for BlackPlutonium vacfreezing in the same file.
> Remove duplicate vac freezer recipe

- src/main/java/com/dreammaster/scripts/ScriptAvaritia.java
- src/main/java/com/dreammaster/scripts/ScriptRailcraft.java
Also resolve magic numbers in the last PR
> Fix 0 EUt recipe

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13552 by making the recipe the same in both machines,
> Change Alveary Sieve Recipe in Assembler

- src/main/java/com/dreammaster/recipes/RecipeRemover.java
- src/main/java/com/dreammaster/scripts/ScriptNatura.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11177
now the clouds give GT sulfur:
> Sulfur Cloud recipe fix

- src/main/java/com/dreammaster/main/MainRegistry.java
- src/main/java/com/dreammaster/scripts/ScriptForbiddenMagic.java
- src/main/java/com/dreammaster/thaumcraft/TCHelper.java
- src/main/java/com/dreammaster/thaumcraft/TCLoader.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13632
Also logs other issues to fix later:
```
[21:06:00] [Client thread/ERROR] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for Thaumcraft:WandCasting:32767 has invalid research name (@WAND_AUGMENTATION_TAINTED_CORE)!
[21:06:00] [Client thread/ERROR] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for Thaumcraft:WandCasting:32767 has invalid research name (@WAND_AUGMENTATION_TAINT_CAPPING)!
[21:06:00] [Client thread/ERROR] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicTinkerer:infusedInkwell:0 has invalid research name (INFUSED_INKWELL)!
[21:06:00] [Client thread/ERROR] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for Enchantment recipe (effectId: 99) has invalid research name …
```
> Fix Silent Dreamwood Rod recipe

- src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
A RA2 fix. outputs are nice. fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13666
> Fix AL recipes

- src/main/java/com/dreammaster/scripts/ScriptChisel.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13670
> Fix end stone chiseling

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/ExtruderRecipes.java
More QOL assembler recipes to further reduce molecular assembler requirements in crafting.
> More qol assembler + extruder recipes + fix assembling line eu cost

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adds new recipes for hempcrete. goes together with https://github.com/GTNewHorizons/Chisel/pull/30
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13702
> new hempcrete recipes

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
suggestion for the new Chisel blocks : HempcreteSand and Hempcrete
> new Hempcretesand & Hempcrete recipe

- src/main/java/com/dreammaster/main/MainRegistry.java
> Dont put New Horizons TC Category on top

- src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
- src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
- src/main/java/com/dreammaster/scripts/ScriptGendustry.java
- src/main/java/com/dreammaster/scripts/ScriptGregtech.java
- src/main/java/com/dreammaster/scripts/ScriptHardcoreEnderExpansion.java
- src/main/java/com/dreammaster/scripts/ScriptHarvestcraft.java
- src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
- src/main/java/com/dreammaster/scripts/ScriptThaumicTinkerer.java
- src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
Reverts GTNewHorizons/NewHorizonsCoreMod#660
Merge with https://github.com/GTNewHorizons/GT5-Unofficial/pull/2118
> Revert "Fix furnace smelting recipes from script conversion"

- dependencies.gradle
- src/main/java/com/dreammaster/config/CoreModConfig.java
> New version

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adding Recipes for the new quad input hatches, umv, uxv and humongus, spacetime in uxv/humongus will be replaced once I or someone else adds universium pipes.
> Recipes for new quad input hatches

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Added several new assembler recipe where previously there was just a crafting recipe with tools. Mostly covers https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13563, only some vague or less clear stuff is left. Might be good to close.
Also continued to clean up the assembler recipe file some more (moved recipes away from the soldering alloy method that dont use soldering alloy, added a few more methods for better organisation, unified the ismodloaded checks for the methods, moved the field gens to the rest of the tiered components).
New recipes: Hastelloy-X Block
Extreme Engine Intake Casing
Steel and Bronze Gear Box
Cell Workbench
Diamond Gear
Needs a small GT PR to add a circuit so that the Steel Gear Box and Solid Steel Machine Casing don't conflict.
> More new assembler recipes

- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
Simple shapeless recipe: dual interface (part/block) + p2p ====> dual interface p2p
> Add dual p2p interface recipe

- dependencies.gradle
- src/main/java/com/dreammaster/bartworksHandler/BioItemLoader.java
- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/GT_CustomLoader.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/FluidExtractorRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/FluidSolidifierRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/FormingPressRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/ImplosionCompressorRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/VacuumFreezerRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
- src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
- src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
- src/main/java/com/dreammaster/scripts/ScriptJABBA.java
- Migrate recipes from AssemblerRecipes.java
- Migrate recipes from MixerRecipes.java
- Migrate recipes from FluidSolidifierRecipes.java
- Migrate recipes from FormingPressRecipes.java
- Migrate recipes from FluidExtractorRecipes.java
- Migrate recipes from ImplosionCompressorRecipes.java
- Materials.Superconductor -> Materials.SuperconductorUHV
> migrate some recipes to RA2

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adding in a better recipe for optical fiber cables so it takes less time to a billion+ optical fibers in an assembler.
> Adding Better Optical Fiber Cable Recipe

- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14068.
nothing else changed:
> Use correct housing in quantum fluid cell recipe

- src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
Next stable (2.5.0), we are removing them.
> Remove backbone recipe for deprecation

- dependencies.gradle
- src/main/java/com/dreammaster/recipes/RecipeRemover.java
- src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
Add a more unified recipe like vanilla shears and RC ones
> Shaers ender io

- src/main/java/com/dreammaster/scripts/ScriptStevesCarts.java
- src/main/java/com/dreammaster/scripts/ScriptWirelessRedstone.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14212
> Use GT molten Obsidian

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14319
I agree that more fluids should be more expensive.
> Swap gated plates for adv. fluid housing

- src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14452
> Fix a recipe conflict

- dependencies.gradle
- src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
for all crafts you need a slime island and an ulv compressor
> add Slime boots and Slimesling recipes

- src/main/java/com/dreammaster/coremod/DreamCoreMod.java
- src/main/java/com/dreammaster/mixin/mixins/early/MixinMinecraft_ConfirmExit.java
- src/main/java/com/dreammaster/mixin/mixins/early/MixinMinecraft_PackIcon.java
> Add window to confirm game exit when clicking the [X] on main game window

- src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java
- src/main/java/com/dreammaster/gthandler/GT_Loader_Batteries.java
convert the last few stragglers to RA2 and convert a use of a BW util for voltage tiers, also added the new TierEU.RECIPE throughout that file.
> small deprecation cleanup

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
resolves https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14497
> fix amount of engine intake casings from recipe

- src/main/java/com/dreammaster/mixin/mixins/early/MixinMinecraft_ConfirmExit.java
> keep dialog boxes unique

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adds assembler recipes to the EBF and Vacuum Freezer controller blocks
> Add EBF and vacuum freezer controller assembler recipes

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
> Add LCR AssemblerRecipes.

- src/main/java/com/dreammaster/auxiliary/NEIGTNewHorizonsConfig.java
Set their names using loaded resources in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/14988
> Remove NEI Item name override

- src/main/java/com/dreammaster/amazingtrophies/AchievementHandler.java
- src/main/java/com/dreammaster/main/MainRegistry.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15003
> Achievementhandler Fixes

- src/main/java/com/dreammaster/scripts/ScriptThaumicEnergistics.java
https://github.com/GTNewHorizons/ThaumicEnergistics/pull/56
> change essentia cells index for ThE

- src/main/java/com/dreammaster/gthandler/recipes/ChemicalBathRecipes.java
https://cdn.discordapp.com/attachments/1058706734920777788/1182294944879235133/image.png?ex=65842cf8&is=6571b7f8&hm=a57ecabcff541647d45dd6a84d3b3b5372b703ce6d5b3eb96944c8392f0fb76d&
https://cdn.discordapp.com/attachments/1058706734920777788/1182295242511220766/image.png?ex=65842d3f&is=6571b83f&hm=41dc058ce51299b4d1133360eca4d70c0908c800234350df6ffba90347aa1d84&
> reduce coolant to prevent positive EU output

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15204
> Fix LCR Controller recipe in assembler

- src/main/java/com/dreammaster/recipes/RecipeRemover.java
- src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
Exchange existing item filter recipe
> add recipe for Limited Itemfilter

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adds a recipe for the horus planet block 
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15301
> Add Horus planet block recipe

- src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java
- src/main/java/com/dreammaster/gthandler/recipes/AutoclaveRecipes.java
they were broken in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/589.
fixes one point in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15405.
> Fix several low-grav recipes

- src/main/java/com/dreammaster/gthandler/recipes/FormingPressRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptGregtech.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15381
> Add 4 missing recipes for drill head mold/shape

- src/main/java/com/dreammaster/scripts/ScriptNuclearControl.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15545
> Use oredict for NC Thermometer recipe

- dependencies.gradle
- src/main/java/com/dreammaster/scripts/ScriptIronChests.java
update deps
* https://github.com/GTNewHorizons/ironchest/pull/16/
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15641
> add recipes for Dark Steel chest

- src/main/java/com/dreammaster/scripts/ScriptIronChests.java
- src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
Related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15676
but there are more
Before
> Rename with new TF changes

- src/main/java/com/dreammaster/scripts/ScriptMagicBees.java
fixes one point in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15676
> Fix apimancer typo in recipe and removal

- src/main/java/com/dreammaster/scripts/ScriptTwilightForest.java
fixes another point in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15676
> Fix new TF door recipes

- gradle.properties
- src/main/java/com/dreammaster/main/ClientProxy.java
- src/main/java/com/dreammaster/main/CommonProxy.java
- src/main/java/com/dreammaster/main/MainRegistry.java
- src/main/java/com/dreammaster/modctt/CustomToolTipsHandler.java
https://github.com/GTNewHorizons/GTNH-Translations/issues/8
> Local-aware custom tooltip config files

- src/main/java/com/dreammaster/gthandler/multiAirFilter/GT_MetaTileEntity_AirFilterBase.java
Some of these problems were mentioned all the way back in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12794, what better time to fix than now.
New tooltips:
No functionality has been changed.
> Improve Electric Air Filter tooltips.

- src/main/java/com/dreammaster/recipes/RecipeRemover.java
- src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
Its all done correctly by GT itself. One just has to leave it alone after that :P
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14664
> fix mahogany recipes

- src/main/java/com/dreammaster/gthandler/recipes/CentrifugeRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/ExtractorRecipes.java
Moved from centrifuge to extractor. Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15951
> Fix dumb hydration cell recipe

- src/main/java/com/dreammaster/coremod/DepLoader.java
- src/main/java/com/dreammaster/coremod/DownloadProgressConsole.java
- src/main/java/com/dreammaster/coremod/DownloadProgressDialog.java
- src/main/java/com/dreammaster/coremod/IDownloadProgress.java
> DreamMasterXXL
— 
Today at 2:19 PM
Hi. Is it possible to add a config or aversion with no download gui ? I never tested if curse version can be executed on a server.
> allow deploader to run in headless environment

- src/main/java/com/dreammaster/scripts/ScriptForbiddenMagic.java
by oredicting the catalyst.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16286
> Fix vinteum nugget recipe

- src/main/java/com/dreammaster/recipes/RecipeRemover.java
- src/main/java/com/dreammaster/scripts/ScriptForestry.java
It uses gold plates as the locking material.
Depends on: https://github.com/GTNewHorizons/ForestryMC/pull/71
> Added the coin backpack recipe

- src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
> Fix recipe typo

- .github/workflows/build-and-test.yml
- dependencies.gradle
Currently doesn't start with the following crash:
```
[17:02:21] [Server thread/ERROR] [FML]: Caught exception from mobsinfo
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
at RFB-Launch//kubatech.api.helpers.ReflectionHelper.getField(ReflectionHelper.java:54) ~[ReflectionHelper.class:?]
at RFB-Launch//kubatech.loaders.MobHandlerLoader.onPostOverridesConfigLoad(MobHandlerLoader.java:234) ~[MobHandlerLoader.class:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler_262_MobHandlerLoader_onPostOverridesConfigLoad_PostMobsOverridesLoadEvent.invoke(.dynamic) ~[?:?]
at RFB-Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
at RFB-Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventB …
```
> Update dependencies post-gt5u-mergening

- src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16404
A plate has the same amount of material as a dust or an ingot, 144mb.
> Fix glue recipe in smeltery

- src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
> Fix computation station being consumed in new quantum anomaly recipe

- src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16480
> Fix mainframe recipe

- src/main/java/com/dreammaster/scripts/ScriptAE2Stuff.java
Adds recipe for Advanced Wireless Setup kit - See https://github.com/GTNewHorizons/ae2stuff/pull/18
> Added recipe for Advanced Wireless Setup Kit

- dependencies.gradle
- src/main/java/com/dreammaster/detrav/ScannerTools.java
- src/main/java/com/dreammaster/main/MainRegistry.java
- src/main/java/com/dreammaster/main/XMod.java
As the title describes. While it might not cause issues, this should probably wait on the [Detrav PR](https://github.com/GTNewHorizons/DetravScannerMod/pull/30).
> Move Detrav recipes to coremod

- src/main/java/com/dreammaster/scripts/ScriptMagicBees.java
by fixing a typo.
fixes https://discord.com/channels/181078474394566657/1029918255932002395/1251915698448371783
> Fix shallow grave tc page

- src/main/java/com/dreammaster/scripts/ScriptAutomagy.java
Yes I got tired of how easy it was to craft
> Edit the Alchemical Boiler Recipe

- src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptBuildCraft.java
- src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
- src/main/java/com/dreammaster/scripts/ScriptExtraUtilities.java
- src/main/java/com/dreammaster/scripts/ScriptGenetics.java
- src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
- src/main/java/com/dreammaster/scripts/ScriptNuclearControl.java
- src/main/java/com/dreammaster/scripts/ScriptOpenBlocks.java
- src/main/java/com/dreammaster/scripts/ScriptOpenModularTurrets.java
- src/main/java/com/dreammaster/scripts/ScriptProjectRed.java
- src/main/java/com/dreammaster/scripts/ScriptStevesFactoryManager.java
- src/main/java/com/dreammaster/scripts/ScriptThaumicEnergistics.java
this is a good code cleanup change on its own.
But additionally, it is needed for https://github.com/GTNewHorizons/GT5-Unofficial/pull/2682.
> Fix many circuit oredicts in nhcoremod

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptBuildCraft.java
- src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
- src/main/java/com/dreammaster/scripts/ScriptExtraUtilities.java
- src/main/java/com/dreammaster/scripts/ScriptGendustry.java
- src/main/java/com/dreammaster/scripts/ScriptGenetics.java
- src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
- src/main/java/com/dreammaster/scripts/ScriptOpenBlocks.java
- src/main/java/com/dreammaster/scripts/ScriptRemoteIO.java
- src/main/java/com/dreammaster/scripts/ScriptStevesFactoryManager.java
- Use oredicted circuits in most of the recipes
- Add a comment to pattern optimization matrix recipe
> Circuit oredict cleanup

- dependencies.gradle
- src/main/java/com/dreammaster/recipes/RecipeRemover.java
- src/main/java/com/dreammaster/scripts/ScriptAkashicTome.java
- src/main/java/com/dreammaster/scripts/ScriptLoader.java
Couldn't get it to work in Dev Env though, got a Dependencies not loaded error.
> Add a new recipe to the Akashic Tome

- src/main/java/com/dreammaster/scripts/ScriptAkashicTome.java
> Fix like this since, enums.Mods don't contain the value for akashic tome yet.

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
goes together with https://github.com/GTNewHorizons/VisualProspecting/pull/48
all looking good:
> Transfer gt recipe from vp and make it RA2

- src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java
https://github.com/GTNewHorizons/Galacticraft/pull/89
> Move gregified recipes from GC to coremod

- dependencies.gradle
- src/main/java/com/dreammaster/galacticgreg/SpaceDimRegisterer.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16746
See also:
- https://github.com/GTNewHorizons/GTNEIOrePlugin/pull/40
- https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16771
> Remove Space from "Mehen Belt"

- src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
> Wireless data recipes

- src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
> Add raw ores to smeltery script

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/FluidHeaterRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptGregtechPlusPlus.java
it won't compile unless https://github.com/GTNewHorizons/GT5-Unofficial/pull/2713 is merged and tagged
> fix removed RA1 calls

- dependencies.gradle
- gradle.properties
- settings.gradle
- src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Added a GTNH recipe for the Fluid extreme universe cell
related
https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/218
> Add universe fluid cell recipe

- src/main/java/com/dreammaster/chisel/ChiselHelper.java
- src/main/java/com/dreammaster/scripts/ScriptForbiddenMagic.java
only had the forbidden magic block twice. This also broke some bee breeding.
now proper:
fixes https://discord.com/channels/181078474394566657/181078474394566657/1267582818578595880
> Fix Netherstar block chiselgroup

- src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
> Fix several bugs in a new ae2fc cell recipe

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/ChemicalBathRecipes.java
Adds recipes for the High Energy Laser Emitter, Laser Containment Casings, and Laser Resistant Plate.
Alloys used are stellite, nitinol 60, and hastelloy-x
> Recipes for HELE and its casings.

- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
- src/main/java/com/dreammaster/scripts/ScriptAkashicTome.java
Back to the old way, The pumps are going away, and the Fluid Processors are returning.
But since there only exist 2 ranks of them,
the components are split between them.
> Readd the Fluid processors to the Fluid Storage Recipes

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java
goes together with https://github.com/GTNewHorizons/Computronics/pull/26
additionally also fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16940
> add gt machine recipes from computronics

- src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
> Added wormhole generator recipe

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12796
> Added jabba redstone and hopper facade assembler recipes

- dependencies.gradle
- src/main/java/com/dreammaster/scripts/ScriptGregtech.java
Loose rationale for parts:
- Piston: disc ejection/insertion mechanism
- Emitter: wireless headphone communication
- Motor: spinning the music discs
- Note blocks: speakers
Headphones:
- Rubber rod: elastic head band
- Sensor: to receive signals from the jukebox
- Noteblocks: speakers
> Add electric jukebox and wireless headphones recipes

- src/main/java/com/dreammaster/scripts/ScriptIronChests.java
- src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
- src/main/java/com/dreammaster/scripts/ScriptTwilightForest.java
Forgot to update pack recipes after we did the below
https://github.com/GTNewHorizons/twilightforest/pull/81
https://github.com/GTNewHorizons/twilightforest/pull/82
> TFPlanks is back to TFPlank

- src/main/java/com/dreammaster/scripts/ScriptChisel.java
adds chisel group for steeleaf blocks
part of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17092
> steeleaf block chisel group

- src/main/java/com/dreammaster/gthandler/GT_CustomLoader.java
Fixes most umv singleblocks missing recipes
> Fix material used for umv circuit

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14590
Checks off second item in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15276
Recipe costs the same materials as crafting
(also I fixed a small typo in another file)
> Add recipe for yott casing

- src/main/java/com/dreammaster/scripts/ScriptGregtech.java
fixes https://discord.com/channels/181078474394566657/522098956491030558/1279445906181198005
> use oredict in recipes for jukebox

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/AutoclaveRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/CuttingMachineRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
- src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
- src/main/java/com/dreammaster/scripts/ScriptAvaritia.java
- src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
- src/main/java/com/dreammaster/scripts/ScriptThaumicEnergistics.java
Lots of impractical voltages in coremod
> Fixed a lot of impractical voltages

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
> Change dyes in monitor recipes

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Adds recipes for Ondrej's fluid solidifier multiblock.
> Added recipes for the fluid solidifier multi

- src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
it wasnt in the log so I missed it :P
> maybe last full amp fix

- src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptAvaritiaAddons.java
Eternal and iron singularity had swapped stats
> Fix swapped recipe times/voltages

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
oops
also fixed the neutronium casing recipe to not randomly take coils
> Don't randomly make infcat cost 8x as much

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17284
only multiblock now:
> Fix mixer recipe

- src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
caused by the supposed "texture work" https://github.com/GTNewHorizons/GT5-Unofficial/pull/3161 that also changed a bunch of fluids.
> fix random pack breakage of the day no2

- src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/ImplosionCompressorRecipes.java
Removes saplings and compressed plates that are handled by oredict in gt5u
> Collisions etc

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
the items are just distinguised by nbt sadly.
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17371
> fix several open blocks assembler recipes

- src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptBloodArsenal.java
- src/main/java/com/dreammaster/scripts/ScriptBuildCraft.java
- src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
- src/main/java/com/dreammaster/scripts/ScriptEMT.java
- src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
- src/main/java/com/dreammaster/scripts/ScriptExtraBees.java
- src/main/java/com/dreammaster/scripts/ScriptForestry.java
Most of these are things that were not using the oredictunificator, also removed lots of recipes that were manually trying to use the removed railcraft plates
> Fix collisions

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/CentrifugeRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/ExtruderRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/ForgeHammerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/FormingPressRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/LatheRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/VacuumFreezerRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
- src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
> Collisions

- src/main/java/com/dreammaster/scripts/ScriptGregtech.java
- src/main/java/com/dreammaster/scripts/ScriptTinkersDefence.java
https://discord.com/channels/181078474394566657/522098956491030558/1288923203762262027
> Apply TiC extruder recipe category

- src/main/java/com/dreammaster/scripts/ScriptArchitectureCraft.java
Adds a recipe to the Glowbrush that was implemented in https://github.com/GTNewHorizons/ArchitectureCraft/pull/19
> Add a recipe to the Architect's Glowbrush

- src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
The ingredient circuit was accidentally oredicted during cleanup
> Fix good circuit recipe

- src/main/java/com/dreammaster/command/AllPurposeDebugCommand.java
- src/main/java/com/dreammaster/command/CustomDropsCommand.java
- src/main/java/com/dreammaster/command/CustomFuelsCommand.java
- src/main/java/com/dreammaster/command/CustomToolTipsCommand.java
- src/main/java/com/dreammaster/command/HazardousItemsCommand.java
- src/main/java/com/dreammaster/command/ItemInHandInfoCommand.java
> remove field allocation holding command aliases in each command

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
> Fix LuV world accelerator assembler recipe

- src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java
For the recipes that are the "last" / highest tier recipe for certain products
> Add full dust recipe for certain bacterial vats recipes

- src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Sister PR of https://github.com/GTNewHorizons/GTNH-Intergalactic/pull/80
> Move space assembler recipes to RA2

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/thaumcraft/TCLoader.java
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17659
- Black Granite
- Dense Ice
- Dark Matter
- Crushed Ice as fluid
> Add Mehen Belt Planet recipe

- src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
Just a small bug I noticed while looking into a different ticket.
The flower is gray according to the oredict and according to other mods. not black. Which yea is indeed its color.
> fix small bop to gt color bug

- src/main/java/com/dreammaster/scripts/ScriptOpenComputers.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17931
> Remove LogFactory from OpenComputers script

- src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
About @Dream-Master 's [comment](https://github.com/GTNewHorizons/EnderIO/pull/179#issuecomment-2469796889) in [here](https://github.com/GTNewHorizons/EnderIO/pull/179)
> Removed Ultra Dense ME conduit recipe

- src/main/java/com/dreammaster/recipes/RecipeRemover.java
Needs to be merged with : https://github.com/GTNewHorizons/GT5-Unofficial/pull/3497
> Delete GT++ Super chests

- src/main/java/com/dreammaster/gthandler/recipes/MaceratorRecipes.java
Partly completes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17081
> 9x Oreberry maceration to remove tiny dust

- src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
Title. Conduit speed downgrade currently only has a recipe with normal rubber.
> Add alt rubbers to conduit speed downgrade

- src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17855
> Fix circuit oredict, nbt sensitivity on universe cells

- src/main/java/com/dreammaster/modcustomdrops/CustomDropsHandler.java
Fix chances over 100%
before
after
> Fix custom drops chances

- src/main/java/com/dreammaster/NHTradeHandler/NHTradeHandler.java
- src/main/java/com/dreammaster/main/MainRegistry.java
nhcoremod part of https://github.com/GTNewHorizons/GT5-Unofficial/pull/3660
> priest trade improvements

- src/main/java/com/dreammaster/detrav/ScannerTools.java
together with https://github.com/GTNewHorizons/GT5-Unofficial/pull/3708 this fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18483
was broken in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1101
> fix electric scanner recipes

- src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18508
> fix all the rocket controller recipes

- src/main/java/com/dreammaster/scripts/ScriptProjectRed.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18513
these changes are no longer relevant due to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/18480, I did in fact do some testing there but missed this.
> Project red tinker fix

- src/main/java/com/dreammaster/recipes/RecipeRemover.java
remove recipes of stone tools
- https://github.com/GTNewHorizons/GT5-Unofficial/pull/3717
- https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/18526
- https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/18527
> remove vanilla stone tools

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
- src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
Fixes changed items due to https://github.com/GTNewHorizons/GTNH-Intergalactic/pull/89 / https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/122.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18548.
> Fix DS Parts Recipes

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
bronze is at 19,2k
need to be removed since it has a NULL item recipe
> remove recipe because turbine is not generated since the cut off is 25k

- src/main/java/com/dreammaster/gthandler/recipes/MaceratorRecipes.java
Companion PR to https://github.com/GTNewHorizons/GT5-Unofficial/pull/3709
> Gravel ore no longer needs manual recipe registration

- src/main/java/com/dreammaster/gthandler/recipes/VacuumFurnaceRecipes.java
followup to https://github.com/GTNewHorizons/GT5-Unofficial/pull/3757
> change circuits of froth recycling with Combs

- src/main/java/com/dreammaster/recipes/RecipeRemover.java
- src/main/java/com/dreammaster/scripts/ScriptGregtechPlusPlus.java
remove recipe meddling in NHCoremod scripts. NHCoremod part of https://github.com/GTNewHorizons/GT5-Unofficial/pull/3753
> fix HV tank recipes 

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16915
Supersedes and closes https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1052
> Add assembler recipes for steam hulls

- src/main/java/com/dreammaster/scripts/ScriptNatura.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18141
> Natura Wood crafting recipes use all saws now

- src/main/java/com/dreammaster/gthandler/recipes/BlastFurnaceRecipes.java
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/134 forgot to change the hot ingot to a cooled ingot in the circuit 1 recipe
> Remove hot mv sc circuit 1

- src/main/java/com/dreammaster/scripts/ScriptLogisticPipes.java
small mistake happened when changing something with circuits, this specific recipe got broken there. Also changed the Carbon for Plastic (look comment of issue)
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18719#issuecomment-2585482681
> fix recipe of Logistics Disk

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Goes with https://github.com/GTNewHorizons/GTNH-Intergalactic/pull/102
This PR will require intergalactic to be re-tagged to merge.
NOTE: #1144 will need to be updated after this merges
> Switch space assembler module tier to metadata

- src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
This makes the DTPF prioritize recipes using higher tier catalysts.
> Order DTPF Recipes by Catalyst Tier

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptAdvancedSolarPanel.java
- src/main/java/com/dreammaster/scripts/ScriptSuperSolarPanels.java
Replaces old solar recipes with gt solars added by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3689
Recipes are identical.
Also adds assembler conversion recipes.
> Convert solar panel recipes

- dependencies.gradle
- src/main/java/com/dreammaster/scripts/ScriptGregtechPlusPlus.java
Requires https://github.com/GTNewHorizons/GT5-Unofficial/pull/3805
> Migrate to new way of specifying QFT catalyst

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Accidentally put these in the ol' soldering loop
> Fix duplicate solar conversion

- src/main/java/com/dreammaster/scripts/ScriptAvaritiaAddons.java
Since there are masses of angry people in general chat, I changed the flowers to runes, I also decreased the number of infinity plates since tablet and pool uses 6, and previously this used 12, now it uses 4 + 8 nuggets, also I added some more rainbow to the recipe
> Asgardandelion 2.0

- src/main/java/com/dreammaster/tinkersConstruct/TiCoLoader.java
> Don't assume block and item IDs don't change at map load

- src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
Fixes https://discord.com/channels/181078474394566657/522098956491030558/1335241144510058506
> Fix some amunra recipes

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Redstone singularity and redstone alloy superdense.
> Add recipe for black hole utility hatch

- src/main/java/com/dreammaster/gthandler/recipes/FluidHeaterRecipes.java
Supports regular and automagy milk (from the thirsty tank with bovine glyph)
Requires [GT5-Unofficial/#3932](https://github.com/GTNewHorizons/GT5-Unofficial/pull/3932)
Closes [GT-New-Horizons/#18978](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18978)
> Add fluid heater recipes for pam's hearvestcraft fresh milk

- src/main/java/com/dreammaster/recipes/ShapelessUniversalRecipe.java
- src/main/java/com/dreammaster/scripts/ScriptGregtech.java
Sorry for those who like to refine mince meat over and over 😔
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19033
> Now you can't craft mince meat out of mince meat

- dependencies.gradle
- src/main/java/com/dreammaster/bartworksHandler/VoidMinerLoader.java
Part of https://github.com/GTNewHorizons/GT5-Unofficial/pull/3949/
> Fix toxic everglades references

- dependencies.gradle
- src/main/java/com/dreammaster/scripts/ScriptLoader.java
- src/main/java/com/dreammaster/scripts/ScriptMatterManipulator.java
> Move matter manipulator recipes to coremod

- src/main/java/com/dreammaster/gthandler/recipes/VacuumFurnaceRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptGregtechPlusPlus.java
Part of https://github.com/GTNewHorizons/GT5-Unofficial/pull/3967
> Coremod updates for Refactoring GT++ 2025-02-17

- src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
- src/main/java/com/dreammaster/scripts/ScriptChisel.java
- src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
- src/main/java/com/dreammaster/scripts/ScriptNatura.java
- src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
- src/main/java/com/dreammaster/scripts/ScriptTwilightForest.java
Added recipes for decorative blocks/ or blocks needed in eoh recipe planets:
- Couds from natura ( Normal, Dark, Sulfur, Coal)
- Ash and Ash block
- Aurora block ( using the helium it gives)
- Blood from queen blood
- Podzol, Mycellium, and grass from Botania seeds
- Honeycomb block
- Blue Slimedirt
- Quicksand
> Qol recipes

- src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
- src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
https://discord.com/channels/181078474394566657/939305179524792340/1342457000499613727
> fix wrong recipes in circuit assemblers for preconfigured storage buses

- gradle.properties
- src/main/java/com/dreammaster/gthandler/GT_Loader_ItemPipes.java
Requires https://github.com/GTNewHorizons/GT5-Unofficial/pull/3983
> Adapt to pipe rename

- src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
Part of https://github.com/GTNewHorizons/GT5-Unofficial/pull/3970
> Coremod updates for Refactoring GT++ 2025-02-19

- dependencies.gradle
- src/main/java/com/dreammaster/modhazardousitems/HazardousItemsHandler.java
I missed this usage when approving https://github.com/GTNewHorizons/GT5-Unofficial/pull/4102
> Hotfix: Reflect change to GT Hazard API

- src/main/java/com/dreammaster/scripts/ScriptThaumcraft.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17461
Adds Fluid Extractor and Compressor Recipes for Quicksilver Drop
> Fix recipe inconsistencies with Quicksilver Drop

- src/main/java/com/dreammaster/recipes/RecipeRemover.java
(when Wooden Rail is removed)
Merge after:
https://github.com/GTNewHorizons/TinkersConstruct/pull/163
> remove woodRail deletion

- .github/workflows/test-forbidden-getmoditems.yml
- .github/workflows/test-forbidden-ismodloaded.yml
- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
- src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
- src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
- src/main/java/com/dreammaster/scripts/ScriptSGCraft.java
Part of https://github.com/GTNewHorizons/GT5-Unofficial/pull/4234
> Intergalactic post merge cleanup

- src/main/java/com/dreammaster/scripts/ScriptBloodMagic.java
fixes: [#19665](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19665)
> fix ritual of Unbinding (Blood Magic)

- src/main/java/com/dreammaster/scripts/ScriptEFR.java
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19930
> Fix the armor stand recipe collision

- src/main/java/com/dreammaster/amazingtrophies/AchievementHandler.java
- src/main/java/com/dreammaster/main/MainRegistry.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18879 and https://discord.com/channels/181078474394566657/522098956491030558/1352372161347588178.
> Achievement Fixes

- src/main/java/com/dreammaster/scripts/ScriptStevesCarts.java
Adds recipes for SC2 Electric Engines (GTNewHorizons/SC2#9)
> Add SC2 Electric Engine Recipes

- src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
closes this: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18769
> Add a way to obtain BOP natura, mixing magic and machines

- src/main/java/com/dreammaster/bartworksHandler/BW_RadHatchMaterial.java
must be merged before https://github.com/GTNewHorizons/GT5-Unofficial/pull/4402 gets into a nightly, otherwise it'll crash
> remove error stack

- dependencies.gradle
- src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java
Add a recipe for blood from hell using the new nether air ( the blood can be used to extract some resources from mobheads)
> Hellish blood recipe

- src/main/java/com/dreammaster/mantle/MantleBookLoader.java
- src/test/java/com/dreammaster/mantle/MantleBookLoaderTest.java
needs to be merged and built before https://github.com/GTNewHorizons/GT5-Unofficial/pull/4541
> Remove reference to deleted IGTMod interface

- src/main/java/com/dreammaster/gthandler/recipes/ForgeHammerRecipes.java
- As title says, just removing unnecessary recipe, more details in issue below. 
- Also removed their supplemental imports
This will fix and close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20468
> Removes Plantball -) Sugarcane Forge Hammer Recipe

- src/main/java/com/dreammaster/client/util/GTNHPauseScreen.java
- src/main/java/com/dreammaster/lib/Refstrings.java
- src/main/java/com/dreammaster/loginhandler/LoginHandler.java
- src/main/resources/assets/dreamcraft/lang/en_US.lang
Advertises wiki.gtnewhorizons.com instead of gtnh.miraheze.org
Also fixes the capitalization to be more consistent with everything else.
> Update MOTD Banner

- src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
- src/main/java/com/dreammaster/scripts/ScriptEFR.java
Add a mixer recipe to get gaia dust instead of using the molecular ingot recipe
Add a recipe to get shulker eggs and shells
> Shulker and qol botania

- src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
- src/main/java/com/dreammaster/scripts/ScriptEFR.java
- Adds a recipe to turn 512000 cobblestone in the neutronium compressor into 1 ae2 singularity, since those are more used now in some multiblocks and void cells
- Correct a typo in one of my recent recipes that was supposed to give 8 and I placed a 1
> Qol singularity

- src/main/java/com/dreammaster/gthandler/recipes/ChemicalBathRecipes.java
- Changes a 2, into a 1. Was there by mistake
> Wire Dupe Fix

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/gthandler/GT_Recipe_Remover.java
- src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21244
Changed the charged battery
to empty one
> Change charged battery to empty for treetap and hoe

- src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Was just an oversight.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21321
> Change BHC Controller Scan to Steel Singularity

- src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Fixes https://discord.com/channels/181078474394566657/522098956491030558/1421481589581283458
> Fix: Make LuV HiAmp Transformer use 2 coils instead of 1

- src/main/java/com/dreammaster/baubles/OvenGlove.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21495
> Remove specific slot check and notification for pizza gloves

- src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
- src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1389 but for the 2.8.x branch
> Fix Barnarda C plank recipes for 2.8.x branch

- dependencies.gradle
- src/main/java/com/dreammaster/scripts/ScriptLoader.java
- src/main/java/com/dreammaster/scripts/ScriptVendingMachine.java
Draft, do not merge.
Build will not succeed for now.
Steps:
1. Publish VM 0.4.0 to maven repo https://nexus.gtnewhorizons.com/#browse/browse:releases:com%2Fcubefury%2Fvendingmachine%2FVendingMachine
2. Add VM to GT5U modlist https://github.com/GTNewHorizons/GT5-Unofficial/pull/5009
3. Update BetterQuesting with VM integration https://github.com/GTNewHorizons/BetterQuesting/pull/176
4. Add Default Trade list to config in main modpack repo https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/21829
5. **Update Coremod with recipes (This PR)**
> Add recipes for vending machine
